<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DireccionesUsuarioTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('DIRECCIONES_USUARIO')->insert([
            [
                'ID_USUARIO' => 1,
                'NOMBRE_COMPLETO' => 'Juan Pérez',
                'CODIGO_POSTAL' => '12345',
                'ESTADO' => 'Ciudad de México',
                'MUNICIPIO' => 'Benito Juárez',
                'COLONIA' => 'Del Valle',
                'CALLE' => 'Av. Insurgentes Sur',
                'NUMERO_EXTERIOR' => '123',
                'NUMERO_INTERIOR' => 'A1',
                'CALLE_1' => 'Xola',
                'CALLE_2' => 'Pilares',
                'CONTACTO' => '5512345678',
                'INDICACIONES' => 'Tocar el timbre rojo',
            ],
            [
                'ID_USUARIO' => 2,
                'NOMBRE_COMPLETO' => 'Ana López',
                'CODIGO_POSTAL' => '67890',
                'ESTADO' => 'Estado de México',
                'MUNICIPIO' => 'Naucalpan',
                'COLONIA' => 'Las Américas',
                'CALLE' => 'Av. Primero de Mayo',
                'NUMERO_EXTERIOR' => '456',
                'NUMERO_INTERIOR' => 'B2',
                'CALLE_1' => 'San Mateo',
                'CALLE_2' => 'Las Torres',
                'CONTACTO' => '5587654321',
                'INDICACIONES' => 'Dejar en recepción',
            ],
            [
                'ID_USUARIO' => 3,
                'NOMBRE_COMPLETO' => 'Carlos Fernández',
                'CODIGO_POSTAL' => '54321',
                'ESTADO' => 'Jalisco',
                'MUNICIPIO' => 'Guadalajara',
                'COLONIA' => 'Chapultepec',
                'CALLE' => 'Av. Chapultepec',
                'NUMERO_EXTERIOR' => '789',
                'NUMERO_INTERIOR' => '2B',
                'CALLE_1' => 'Niños Héroes',
                'CALLE_2' => 'Américas',
                'CONTACTO' => '3312345678',
                'INDICACIONES' => 'Tocar dos veces el timbre',
            ],
            [
                'ID_USUARIO' => 4,
                'NOMBRE_COMPLETO' => 'María González',
                'CODIGO_POSTAL' => '98765',
                'ESTADO' => 'Nuevo León',
                'MUNICIPIO' => 'Monterrey',
                'COLONIA' => 'San Pedro Garza García',
                'CALLE' => 'Calzada del Valle',
                'NUMERO_EXTERIOR' => '111',
                'NUMERO_INTERIOR' => 'PH',
                'CALLE_1' => 'Gómez Morín',
                'CALLE_2' => 'Humberto Lobo',
                'CONTACTO' => '8187654321',
                'INDICACIONES' => 'Dejar en la caseta de seguridad',
            ],
            [
                'ID_USUARIO' => 5,
                'NOMBRE_COMPLETO' => 'Lucía Ramírez',
                'CODIGO_POSTAL' => '11223',
                'ESTADO' => 'Puebla',
                'MUNICIPIO' => 'Puebla',
                'COLONIA' => 'La Paz',
                'CALLE' => 'Av. Juárez',
                'NUMERO_EXTERIOR' => '202',
                'NUMERO_INTERIOR' => '3C',
                'CALLE_1' => '13 Sur',
                'CALLE_2' => '16 de Septiembre',
                'CONTACTO' => '2221234567',
                'INDICACIONES' => 'Tocar el timbre blanco',
            ],
            [
                'ID_USUARIO' => 6,
                'NOMBRE_COMPLETO' => 'Fernando Martínez',
                'CODIGO_POSTAL' => '33445',
                'ESTADO' => 'Querétaro',
                'MUNICIPIO' => 'Querétaro',
                'COLONIA' => 'Centro',
                'CALLE' => '5 de Febrero',
                'NUMERO_EXTERIOR' => '909',
                'NUMERO_INTERIOR' => '4A',
                'CALLE_1' => 'Constituyentes',
                'CALLE_2' => 'Zaragoza',
                'CONTACTO' => '4421234567',
                'INDICACIONES' => 'Frente a la plaza principal',
            ],
            [
                'ID_USUARIO' => 7,
                'NOMBRE_COMPLETO' => 'Rosa Méndez',
                'CODIGO_POSTAL' => '55667',
                'ESTADO' => 'Yucatán',
                'MUNICIPIO' => 'Mérida',
                'COLONIA' => 'Centro',
                'CALLE' => 'Paseo de Montejo',
                'NUMERO_EXTERIOR' => '123',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Calle 60',
                'CALLE_2' => 'Calle 47',
                'CONTACTO' => '9998765432',
                'INDICACIONES' => 'Dejar en la recepción del hotel',
            ],
            [
                'ID_USUARIO' => 8,
                'NOMBRE_COMPLETO' => 'Gabriel Ruiz',
                'CODIGO_POSTAL' => '66778',
                'ESTADO' => 'Veracruz',
                'MUNICIPIO' => 'Veracruz',
                'COLONIA' => 'Centro Histórico',
                'CALLE' => 'Malecón',
                'NUMERO_EXTERIOR' => '45',
                'NUMERO_INTERIOR' => '1',
                'CALLE_1' => 'Calle Independencia',
                'CALLE_2' => 'Calle 16 de Septiembre',
                'CONTACTO' => '2291234567',
                'INDICACIONES' => 'Dejar en la entrada principal',
            ],
            [
                'ID_USUARIO' => 9,
                'NOMBRE_COMPLETO' => 'Laura Gómez',
                'CODIGO_POSTAL' => '77889',
                'ESTADO' => 'Morelos',
                'MUNICIPIO' => 'Cuernavaca',
                'COLONIA' => 'Vista Hermosa',
                'CALLE' => 'Av. San Diego',
                'NUMERO_EXTERIOR' => '200',
                'NUMERO_INTERIOR' => '6B',
                'CALLE_1' => 'Paseo del Conquistador',
                'CALLE_2' => 'Diana',
                'CONTACTO' => '7778765432',
                'INDICACIONES' => 'Dejar en la entrada de la casa',
            ],
            [
                'ID_USUARIO' => 10,
                'NOMBRE_COMPLETO' => 'Mario Torres',
                'CODIGO_POSTAL' => '44556',
                'ESTADO' => 'Guanajuato',
                'MUNICIPIO' => 'León',
                'COLONIA' => 'Centro',
                'CALLE' => 'Madero',
                'NUMERO_EXTERIOR' => '350',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Allende',
                'CALLE_2' => 'Hidalgo',
                'CONTACTO' => '4771234567',
                'INDICACIONES' => 'Dejar en recepción',
            ],
            [
                'ID_USUARIO' => 11,
                'NOMBRE_COMPLETO' => 'Adriana Flores',
                'CODIGO_POSTAL' => '55443',
                'ESTADO' => 'Baja California',
                'MUNICIPIO' => 'Tijuana',
                'COLONIA' => 'Zona Río',
                'CALLE' => 'Av. Paseo de los Héroes',
                'NUMERO_EXTERIOR' => '500',
                'NUMERO_INTERIOR' => '7D',
                'CALLE_1' => 'Calle Segunda',
                'CALLE_2' => 'Abelardo L. Rodríguez',
                'CONTACTO' => '6648765432',
                'INDICACIONES' => 'Dejar con seguridad',
            ],
            [
                'ID_USUARIO' => 12,
                'NOMBRE_COMPLETO' => 'Elena Ríos',
                'CODIGO_POSTAL' => '11234',
                'ESTADO' => 'Chihuahua',
                'MUNICIPIO' => 'Ciudad Juárez',
                'COLONIA' => 'Las Torres',
                'CALLE' => 'Av. Tecnológico',
                'NUMERO_EXTERIOR' => '405',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Francisco Villa',
                'CALLE_2' => 'Torres del Lago',
                'CONTACTO' => '6561234567',
                'INDICACIONES' => 'Dejar con el portero',
            ],
            [
                'ID_USUARIO' => 13,
                'NOMBRE_COMPLETO' => 'Diego Cabrera',
                'CODIGO_POSTAL' => '23456',
                'ESTADO' => 'Sonora',
                'MUNICIPIO' => 'Hermosillo',
                'COLONIA' => 'Villa de Seris',
                'CALLE' => 'Blvd. Kino',
                'NUMERO_EXTERIOR' => '123',
                'NUMERO_INTERIOR' => '1A',
                'CALLE_1' => 'Av. Serdán',
                'CALLE_2' => 'Garmendia',
                'CONTACTO' => '6628765432',
                'INDICACIONES' => 'Tocar el timbre de la derecha',
            ],
            [
                'ID_USUARIO' => 14,
                'NOMBRE_COMPLETO' => 'Valeria Muñoz',
                'CODIGO_POSTAL' => '33456',
                'ESTADO' => 'Tabasco',
                'MUNICIPIO' => 'Villahermosa',
                'COLONIA' => 'Tabasco 2000',
                'CALLE' => 'Av. Universidad',
                'NUMERO_EXTERIOR' => '789',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Paseo Tabasco',
                'CALLE_2' => 'Rovirosa',
                'CONTACTO' => '9931234567',
                'INDICACIONES' => 'Dejar con la recepcionista',
            ],
            [
                'ID_USUARIO' => 15,
                'NOMBRE_COMPLETO' => 'Oscar Vázquez',
                'CODIGO_POSTAL' => '44567',
                'ESTADO' => 'Coahuila',
                'MUNICIPIO' => 'Saltillo',
                'COLONIA' => 'Mirasierra',
                'CALLE' => 'Blvd. Venustiano Carranza',
                'NUMERO_EXTERIOR' => '998',
                'NUMERO_INTERIOR' => '2B',
                'CALLE_1' => 'Periférico Luis Echeverría',
                'CALLE_2' => 'Alameda Zaragoza',
                'CONTACTO' => '8448765432',
                'INDICACIONES' => 'Dejar en el buzón',
            ],
            [
                'ID_USUARIO' => 16,
                'NOMBRE_COMPLETO' => 'Patricia Jiménez',
                'CODIGO_POSTAL' => '55678',
                'ESTADO' => 'Querétaro',
                'MUNICIPIO' => 'Querétaro',
                'COLONIA' => 'Milenio III',
                'CALLE' => 'Prol. Constituyentes',
                'NUMERO_EXTERIOR' => '23',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Bernardo Quintana',
                'CALLE_2' => 'Centro Sur',
                'CONTACTO' => '4428765432',
                'INDICACIONES' => 'Tocar dos veces el timbre',
            ],
            [
                'ID_USUARIO' => 17,
                'NOMBRE_COMPLETO' => 'Samuel Morales',
                'CODIGO_POSTAL' => '66789',
                'ESTADO' => 'Yucatán',
                'MUNICIPIO' => 'Mérida',
                'COLONIA' => 'Itzimná',
                'CALLE' => 'Calle 21',
                'NUMERO_EXTERIOR' => '45',
                'NUMERO_INTERIOR' => 'C',
                'CALLE_1' => 'Calle 22',
                'CALLE_2' => 'Av. Colón',
                'CONTACTO' => '9991234567',
                'INDICACIONES' => 'Dejar en la puerta principal',
            ],
            [
                'ID_USUARIO' => 18,
                'NOMBRE_COMPLETO' => 'Lorena Salazar',
                'CODIGO_POSTAL' => '77890',
                'ESTADO' => 'Morelos',
                'MUNICIPIO' => 'Temixco',
                'COLONIA' => 'Centro',
                'CALLE' => 'Calle Hidalgo',
                'NUMERO_EXTERIOR' => '68',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Calle Morelos',
                'CALLE_2' => 'Av. Reforma',
                'CONTACTO' => '7771234567',
                'INDICACIONES' => 'Tocar el timbre verde',
            ],
            [
                'ID_USUARIO' => 19,
                'NOMBRE_COMPLETO' => 'Gustavo Pérez',
                'CODIGO_POSTAL' => '88901',
                'ESTADO' => 'Michoacán',
                'MUNICIPIO' => 'Morelia',
                'COLONIA' => 'Chapultepec',
                'CALLE' => 'Calzada Juárez',
                'NUMERO_EXTERIOR' => '150',
                'NUMERO_INTERIOR' => '3',
                'CALLE_1' => 'Av. Acueducto',
                'CALLE_2' => 'Tata Vasco',
                'CONTACTO' => '4439876543',
                'INDICACIONES' => 'Dejar en el buzón de la entrada',
            ],
            [
                'ID_USUARIO' => 20,
                'NOMBRE_COMPLETO' => 'Carolina Torres',
                'CODIGO_POSTAL' => '99012',
                'ESTADO' => 'Oaxaca',
                'MUNICIPIO' => 'Oaxaca de Juárez',
                'COLONIA' => 'Centro',
                'CALLE' => 'Macedonio Alcalá',
                'NUMERO_EXTERIOR' => '89',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Av. Independencia',
                'CALLE_2' => 'Garcia Vigil',
                'CONTACTO' => '9511234567',
                'INDICACIONES' => 'Dejar con el vigilante',
            ],
            [
                'ID_USUARIO' => 21,
                'NOMBRE_COMPLETO' => 'Jorge Lozano',
                'CODIGO_POSTAL' => '10123',
                'ESTADO' => 'Durango',
                'MUNICIPIO' => 'Durango',
                'COLONIA' => 'Zona Centro',
                'CALLE' => 'Constitución',
                'NUMERO_EXTERIOR' => '321',
                'NUMERO_INTERIOR' => '4A',
                'CALLE_1' => 'Guadiana',
                'CALLE_2' => 'Calle Victoria',
                'CONTACTO' => '6181234567',
                'INDICACIONES' => 'Dejar en recepción del edificio',
            ],
            [
                'ID_USUARIO' => 22,
                'NOMBRE_COMPLETO' => 'Fernando Ortega',
                'CODIGO_POSTAL' => '87654',
                'ESTADO' => 'Guerrero',
                'MUNICIPIO' => 'Acapulco',
                'COLONIA' => 'Costa Azul',
                'CALLE' => 'Av. Costera Miguel Alemán',
                'NUMERO_EXTERIOR' => '202',
                'NUMERO_INTERIOR' => 'B4',
                'CALLE_1' => 'Av. Universidad',
                'CALLE_2' => 'Náutica',
                'CONTACTO' => '7441234567',
                'INDICACIONES' => 'Dejar en la recepción del hotel',
            ],
            [
                'ID_USUARIO' => 23,
                'NOMBRE_COMPLETO' => 'Mariana Soto',
                'CODIGO_POSTAL' => '54321',
                'ESTADO' => 'Puebla',
                'MUNICIPIO' => 'Cholula',
                'COLONIA' => 'Centro',
                'CALLE' => 'Av. 5 de Mayo',
                'NUMERO_EXTERIOR' => '100',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Av. Morelos',
                'CALLE_2' => 'Av. Juárez',
                'CONTACTO' => '2228765432',
                'INDICACIONES' => 'Dejar en la puerta principal',
            ],
            [
                'ID_USUARIO' => 24,
                'NOMBRE_COMPLETO' => 'Cristina Navarro',
                'CODIGO_POSTAL' => '90876',
                'ESTADO' => 'Tamaulipas',
                'MUNICIPIO' => 'Tampico',
                'COLONIA' => 'Altavista',
                'CALLE' => 'Blvd. López Mateos',
                'NUMERO_EXTERIOR' => '56',
                'NUMERO_INTERIOR' => '2A',
                'CALLE_1' => 'Av. Hidalgo',
                'CALLE_2' => 'Universidad',
                'CONTACTO' => '8339876543',
                'INDICACIONES' => 'Dejar con el guardia de seguridad',
            ],
            [
                'ID_USUARIO' => 25,
                'NOMBRE_COMPLETO' => 'Luis Sánchez',
                'CODIGO_POSTAL' => '76543',
                'ESTADO' => 'Baja California',
                'MUNICIPIO' => 'Ensenada',
                'COLONIA' => 'Chapultepec',
                'CALLE' => 'Calle Primera',
                'NUMERO_EXTERIOR' => '120',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Calle Miramar',
                'CALLE_2' => 'Juárez',
                'CONTACTO' => '6461234567',
                'INDICACIONES' => 'Dejar en recepción',
            ],
            [
                'ID_USUARIO' => 26,
                'NOMBRE_COMPLETO' => 'Paola Martínez',
                'CODIGO_POSTAL' => '65432',
                'ESTADO' => 'Zacatecas',
                'MUNICIPIO' => 'Fresnillo',
                'COLONIA' => 'Centro',
                'CALLE' => 'Av. Hidalgo',
                'NUMERO_EXTERIOR' => '450',
                'NUMERO_INTERIOR' => '3B',
                'CALLE_1' => 'González Ortega',
                'CALLE_2' => 'Morelos',
                'CONTACTO' => '4939876543',
                'INDICACIONES' => 'Dejar en la entrada principal',
            ],
            [
                'ID_USUARIO' => 27,
                'NOMBRE_COMPLETO' => 'Claudia Ruiz',
                'CODIGO_POSTAL' => '54312',
                'ESTADO' => 'San Luis Potosí',
                'MUNICIPIO' => 'Ciudad Valles',
                'COLONIA' => 'Vista Hermosa',
                'CALLE' => 'Calle Reforma',
                'NUMERO_EXTERIOR' => '88',
                'NUMERO_INTERIOR' => '4A',
                'CALLE_1' => 'Benito Juárez',
                'CALLE_2' => 'Carranza',
                'CONTACTO' => '4811234567',
                'INDICACIONES' => 'Dejar en la recepción',
            ],
            [
                'ID_USUARIO' => 28,
                'NOMBRE_COMPLETO' => 'Daniela Flores',
                'CODIGO_POSTAL' => '87654',
                'ESTADO' => 'Campeche',
                'MUNICIPIO' => 'Ciudad del Carmen',
                'COLONIA' => 'Centro',
                'CALLE' => 'Calle 31',
                'NUMERO_EXTERIOR' => '34',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Calle 28',
                'CALLE_2' => 'Calle 29',
                'CONTACTO' => '9381234567',
                'INDICACIONES' => 'Dejar en el buzón de correspondencia',
            ],
            [
                'ID_USUARIO' => 29,
                'NOMBRE_COMPLETO' => 'Rodrigo Guzmán',
                'CODIGO_POSTAL' => '90876',
                'ESTADO' => 'Aguascalientes',
                'MUNICIPIO' => 'Aguascalientes',
                'COLONIA' => 'Residencial del Valle',
                'CALLE' => 'Av. Universidad',
                'NUMERO_EXTERIOR' => '678',
                'NUMERO_INTERIOR' => '5B',
                'CALLE_1' => 'Av. Aguascalientes',
                'CALLE_2' => 'Av. Independencia',
                'CONTACTO' => '4499876543',
                'INDICACIONES' => 'Tocar el timbre dos veces',
            ],
            [
                'ID_USUARIO' => 30,
                'NOMBRE_COMPLETO' => 'Alicia Moreno',
                'CODIGO_POSTAL' => '32145',
                'ESTADO' => 'Hidalgo',
                'MUNICIPIO' => 'Pachuca',
                'COLONIA' => 'Real de la Plata',
                'CALLE' => 'Blvd. Felipe Ángeles',
                'NUMERO_EXTERIOR' => '789',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Av. Revolución',
                'CALLE_2' => 'Av. Juárez',
                'CONTACTO' => '7711234567',
                'INDICACIONES' => 'Dejar en la entrada de seguridad',
            ],
            [
                'ID_USUARIO' => 31,
                'NOMBRE_COMPLETO' => 'Roberto Ramírez',
                'CODIGO_POSTAL' => '43210',
                'ESTADO' => 'Tlaxcala',
                'MUNICIPIO' => 'Apizaco',
                'COLONIA' => 'San Luis',
                'CALLE' => 'Av. Hidalgo',
                'NUMERO_EXTERIOR' => '210',
                'NUMERO_INTERIOR' => 'A3',
                'CALLE_1' => 'Av. Juárez',
                'CALLE_2' => 'Independencia',
                'CONTACTO' => '2418765432',
                'INDICACIONES' => 'Tocar el timbre negro',
            ],
            [
                'ID_USUARIO' => 32,
                'NOMBRE_COMPLETO' => 'Elena Castillo',
                'CODIGO_POSTAL' => '65432',
                'ESTADO' => 'Querétaro',
                'MUNICIPIO' => 'Querétaro',
                'COLONIA' => 'Juriquilla',
                'CALLE' => 'Paseo de la República',
                'NUMERO_EXTERIOR' => '245',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Camino Real',
                'CALLE_2' => 'Av. Cimatario',
                'CONTACTO' => '4421234567',
                'INDICACIONES' => 'Dejar en la caseta de vigilancia',
            ],
            [
                'ID_USUARIO' => 33,
                'NOMBRE_COMPLETO' => 'Francisco Torres',
                'CODIGO_POSTAL' => '54321',
                'ESTADO' => 'Morelos',
                'MUNICIPIO' => 'Cuernavaca',
                'COLONIA' => 'Lomas de Cortés',
                'CALLE' => 'Blvd. Cuauhnáhuac',
                'NUMERO_EXTERIOR' => '159',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Colón',
                'CALLE_2' => 'Zapata',
                'CONTACTO' => '7771234567',
                'INDICACIONES' => 'Tocar el timbre al llegar',
            ],
            [
                'ID_USUARIO' => 34,
                'NOMBRE_COMPLETO' => 'Gabriela Vargas',
                'CODIGO_POSTAL' => '45678',
                'ESTADO' => 'Durango',
                'MUNICIPIO' => 'Durango',
                'COLONIA' => 'Centro',
                'CALLE' => 'Av. 20 de Noviembre',
                'NUMERO_EXTERIOR' => '112',
                'NUMERO_INTERIOR' => '4B',
                'CALLE_1' => 'Constitución',
                'CALLE_2' => 'Morelos',
                'CONTACTO' => '6189876543',
                'INDICACIONES' => 'Dejar en la entrada principal',
            ],
            [
                'ID_USUARIO' => 35,
                'NOMBRE_COMPLETO' => 'Ignacio López',
                'CODIGO_POSTAL' => '56789',
                'ESTADO' => 'Michoacán',
                'MUNICIPIO' => 'Morelia',
                'COLONIA' => 'Vista Bella',
                'CALLE' => 'Calle Acueducto',
                'NUMERO_EXTERIOR' => '58',
                'NUMERO_INTERIOR' => '3C',
                'CALLE_1' => 'Río Chiquito',
                'CALLE_2' => 'La Loma',
                'CONTACTO' => '4438765432',
                'INDICACIONES' => 'Dejar en el buzón',
            ],
            [
                'ID_USUARIO' => 36,
                'NOMBRE_COMPLETO' => 'Oscar Jiménez',
                'CODIGO_POSTAL' => '87654',
                'ESTADO' => 'Colima',
                'MUNICIPIO' => 'Manzanillo',
                'COLONIA' => 'Salagua',
                'CALLE' => 'Av. Lázaro Cárdenas',
                'NUMERO_EXTERIOR' => '12',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Miguel de la Madrid',
                'CALLE_2' => 'Jardinero',
                'CONTACTO' => '3149876543',
                'INDICACIONES' => 'Dejar en la oficina de seguridad',
            ],
            [
                'ID_USUARIO' => 37,
                'NOMBRE_COMPLETO' => 'Rosa Martínez',
                'CODIGO_POSTAL' => '43210',
                'ESTADO' => 'Tabasco',
                'MUNICIPIO' => 'Villahermosa',
                'COLONIA' => 'Tabasco 2000',
                'CALLE' => 'Paseo Tabasco',
                'NUMERO_EXTERIOR' => '430',
                'NUMERO_INTERIOR' => '2B',
                'CALLE_1' => 'Av. México',
                'CALLE_2' => 'Laguna',
                'CONTACTO' => '9931234567',
                'INDICACIONES' => 'Dejar en recepción',
            ],
            [
                'ID_USUARIO' => 38,
                'NOMBRE_COMPLETO' => 'Alberto Vargas',
                'CODIGO_POSTAL' => '76543',
                'ESTADO' => 'Nayarit',
                'MUNICIPIO' => 'Tepic',
                'COLONIA' => 'Los Sauces',
                'CALLE' => 'Blvd. Luis Donaldo Colosio',
                'NUMERO_EXTERIOR' => '85',
                'NUMERO_INTERIOR' => '1A',
                'CALLE_1' => 'Calzada del Rey',
                'CALLE_2' => 'Los Cedros',
                'CONTACTO' => '3119876543',
                'INDICACIONES' => 'Dejar en la entrada de la unidad',
            ],
            [
                'ID_USUARIO' => 39,
                'NOMBRE_COMPLETO' => 'Miguel Ángel Gómez',
                'CODIGO_POSTAL' => '65478',
                'ESTADO' => 'Sonora',
                'MUNICIPIO' => 'Hermosillo',
                'COLONIA' => 'San Benito',
                'CALLE' => 'Blvd. Kino',
                'NUMERO_EXTERIOR' => '32',
                'NUMERO_INTERIOR' => '3A',
                'CALLE_1' => 'Luis Encinas',
                'CALLE_2' => 'Morelos',
                'CONTACTO' => '6621234567',
                'INDICACIONES' => 'Dejar con el guardia',
            ],
            [
                'ID_USUARIO' => 40,
                'NOMBRE_COMPLETO' => 'Teresa Domínguez',
                'CODIGO_POSTAL' => '43212',
                'ESTADO' => 'Veracruz',
                'MUNICIPIO' => 'Xalapa',
                'COLONIA' => 'El Mirador',
                'CALLE' => 'Av. 20 de Noviembre',
                'NUMERO_EXTERIOR' => '112',
                'NUMERO_INTERIOR' => '',
                'CALLE_1' => 'Lázaro Cárdenas',
                'CALLE_2' => 'Miguel Alemán',
                'CONTACTO' => '2289876543',
                'INDICACIONES' => 'Tocar el timbre dos veces',
            ],

        ]);
    }
}
