<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('PRODUCTOS')->insert([
            // Belleza y Cuidado Personal
        [
            'MARCA' => 'Nivea',
            'NOMBRE_PRODUCTO' => 'Crema Corporal Nivea Soft',
            'DESCRIPCION_PRODUCTO' => 'Crema hidratante para uso diario.',
            'CARACTERISTICAS_PRODUCTO' => 'Textura ligera, absorción rápida.',
            'PRECIO' => 150.00,
            'CANTIDAD_VENDIDOS' => 200,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 50,
            'IMAGEN' => 'https://th.bing.com/th/id/R.6ed135b9f6dfbcb6eac062a97f47e847?rik=st4OJlqCmhZ%2f9w&pid=ImgRaw&r=0',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 1,
            'COLORES_DISPONIBLES' => null,
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Maybelline',
            'NOMBRE_PRODUCTO' => 'Máscara de Pestañas Lash Sensational',
            'DESCRIPCION_PRODUCTO' => 'Máscara de pestañas con efecto de abanico.',
            'CARACTERISTICAS_PRODUCTO' => 'A prueba de agua, volumen extremo.',
            'PRECIO' => 200.00,
            'CANTIDAD_VENDIDOS' => 350,
            'PRECIO_CON_DESCUENTO' => 180.00,
            'PORCENTAJES_DESCUENTOS' => 10.0,
            'STOCK' => 100,
            'IMAGEN' => 'lash-sensational.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 1,
            'COLORES_DISPONIBLES' => 'Negro',
            'TIPO_ENVIO' => 'express'
        ],
        [
            'MARCA' => 'Colgate',
            'NOMBRE_PRODUCTO' => 'Pasta Dental Colgate Total 12',
            'DESCRIPCION_PRODUCTO' => 'Pasta dental para una protección completa.',
            'CARACTERISTICAS_PRODUCTO' => 'Protección 12 horas, combate el mal aliento.',
            'PRECIO' => 50.00,
            'CANTIDAD_VENDIDOS' => 500,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 200,
            'IMAGEN' => 'colgate-total.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 1,
            'COLORES_DISPONIBLES' => null,
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Pantene',
            'NOMBRE_PRODUCTO' => 'Shampoo Pantene Pro-V',
            'DESCRIPCION_PRODUCTO' => 'Shampoo fortalecedor con Pro-V.',
            'CARACTERISTICAS_PRODUCTO' => 'Cabello fuerte y saludable.',
            'PRECIO' => 120.00,
            'CANTIDAD_VENDIDOS' => 150,
            'PRECIO_CON_DESCUENTO' => 110.00,
            'PORCENTAJES_DESCUENTOS' => 8.3,
            'STOCK' => 80,
            'IMAGEN' => 'pantene-shampoo.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 1,
            'COLORES_DISPONIBLES' => null,
            'TIPO_ENVIO' => 'internacional'
        ],
        [
            'MARCA' => 'Dove',
            'NOMBRE_PRODUCTO' => 'Jabón de Tocador Dove Original',
            'DESCRIPCION_PRODUCTO' => 'Jabón de tocador con hidratación profunda.',
            'CARACTERISTICAS_PRODUCTO' => 'Suave para la piel, con crema hidratante.',
            'PRECIO' => 20.00,
            'CANTIDAD_VENDIDOS' => 1000,
            'PRECIO_CON_DESCUENTO' => 18.00,
            'PORCENTAJES_DESCUENTOS' => 10.0,
            'STOCK' => 500,
            'IMAGEN' => 'dove-jabon.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 1,
            'COLORES_DISPONIBLES' => null,
            'TIPO_ENVIO' => 'estándar'
        ],

        // Accesorios para Autos
        [
            'MARCA' => 'Pioneer',
            'NOMBRE_PRODUCTO' => 'Estéreo para Auto Pioneer DEH-S31BT',
            'DESCRIPCION_PRODUCTO' => 'Estéreo con Bluetooth y entrada USB.',
            'CARACTERISTICAS_PRODUCTO' => 'Conectividad Bluetooth, control de smartphone.',
            'PRECIO' => 1500.00,
            'CANTIDAD_VENDIDOS' => 50,
            'PRECIO_CON_DESCUENTO' => 1350.00,
            'PORCENTAJES_DESCUENTOS' => 10.0,
            'STOCK' => 20,
            'IMAGEN' => 'https://th.bing.com/th/id/R.6ed135b9f6dfbcb6eac062a97f47e847?rik=st4OJlqCmhZ%2f9w&pid=ImgRaw&r=0',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 2,
            'COLORES_DISPONIBLES' => 'Negro',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Michelin',
            'NOMBRE_PRODUCTO' => 'Llanta Michelin 205/55 R16',
            'DESCRIPCION_PRODUCTO' => 'Llanta de alto rendimiento para automóvil.',
            'CARACTERISTICAS_PRODUCTO' => 'Durabilidad, buen agarre en seco y mojado.',
            'PRECIO' => 1200.00,
            'CANTIDAD_VENDIDOS' => 30,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 15,
            'IMAGEN' => 'michelin-llanta.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 2,
            'COLORES_DISPONIBLES' => 'Negro',
            'TIPO_ENVIO' => 'express'
        ],
        [
            'MARCA' => 'Bosch',
            'NOMBRE_PRODUCTO' => 'Juego de Limpiaparabrisas Bosch Aerotwin',
            'DESCRIPCION_PRODUCTO' => 'Limpiaparabrisas de alta calidad y durabilidad.',
            'CARACTERISTICAS_PRODUCTO' => 'Silencioso, limpio y eficiente.',
            'PRECIO' => 400.00,
            'CANTIDAD_VENDIDOS' => 70,
            'PRECIO_CON_DESCUENTO' => 360.00,
            'PORCENTAJES_DESCUENTOS' => 10.0,
            'STOCK' => 30,
            'IMAGEN' => 'bosch-limpiaparabrisas.jpg',
            'ID_VENDEDOR' => 4,
            'ID_CATEGORIA' => 2,
            'COLORES_DISPONIBLES' => null,
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => '3M',
            'NOMBRE_PRODUCTO' => 'Protector de pintura 3M transparente',
            'DESCRIPCION_PRODUCTO' => 'Protección para la pintura del auto.',
            'CARACTERISTICAS_PRODUCTO' => 'Durable, resistente a rayones.',
            'PRECIO' => 200.00,
            'CANTIDAD_VENDIDOS' => 150,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 60,
            'IMAGEN' => '3m-protector.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 2,
            'COLORES_DISPONIBLES' => 'Transparente',
            'TIPO_ENVIO' => 'internacional'
        ],
        [
            'MARCA' => 'Meguiar\'s',
            'NOMBRE_PRODUCTO' => 'Cera para Autos Meguiar\'s Ultimate',
            'DESCRIPCION_PRODUCTO' => 'Cera líquida para brillo y protección.',
            'CARACTERISTICAS_PRODUCTO' => 'Fácil de aplicar, no deja residuos.',
            'PRECIO' => 250.00,
            'CANTIDAD_VENDIDOS' => 200,
            'PRECIO_CON_DESCUENTO' => 225.00,
            'PORCENTAJES_DESCUENTOS' => 10.0,
            'STOCK' => 100,
            'IMAGEN' => 'meguiars-cera.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 2,
            'COLORES_DISPONIBLES' => null,
            'TIPO_ENVIO' => 'estándar'
        ],
        // Animales y Mascotas
        [
            'MARCA' => 'Pedigree',
            'NOMBRE_PRODUCTO' => 'Croquetas para Perro Pedigree Adulto',
            'DESCRIPCION_PRODUCTO' => 'Alimento completo y balanceado para perros adultos.',
            'CARACTERISTICAS_PRODUCTO' => 'Sabor a carne, fortalecimiento de huesos.',
            'PRECIO' => 300.00,
            'CANTIDAD_VENDIDOS' => 200,
            'PRECIO_CON_DESCUENTO' => 270.00,
            'PORCENTAJES_DESCUENTOS' => 10.0,
            'STOCK' => 100,
            'IMAGEN' => 'pedigree-croquetas.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 3,
            'COLORES_DISPONIBLES' => null,
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Fancy Feast',
            'NOMBRE_PRODUCTO' => 'Alimento para Gato Fancy Feast Paté',
            'DESCRIPCION_PRODUCTO' => 'Comida premium enlatada para gatos.',
            'CARACTERISTICAS_PRODUCTO' => 'Textura paté, sin colorantes artificiales.',
            'PRECIO' => 25.00,
            'CANTIDAD_VENDIDOS' => 300,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 500,
            'IMAGEN' => 'fancyfeast-pate.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 3,
            'COLORES_DISPONIBLES' => null,
            'TIPO_ENVIO' => 'express'
        ],
        [
            'MARCA' => 'KONG',
            'NOMBRE_PRODUCTO' => 'Juguete para Perro KONG Classic',
            'DESCRIPCION_PRODUCTO' => 'Juguete rellenable para perros de todas las edades.',
            'CARACTERISTICAS_PRODUCTO' => 'Resistente, ideal para morder.',
            'PRECIO' => 150.00,
            'CANTIDAD_VENDIDOS' => 120,
            'PRECIO_CON_DESCUENTO' => 135.00,
            'PORCENTAJES_DESCUENTOS' => 10.0,
            'STOCK' => 80,
            'IMAGEN' => 'kong-classic.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 3,
            'COLORES_DISPONIBLES' => 'Rojo',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Hartz',
            'NOMBRE_PRODUCTO' => 'Arenero para Gatos Hartz Clean Comfort',
            'DESCRIPCION_PRODUCTO' => 'Arenero para gatos de fácil limpieza.',
            'CARACTERISTICAS_PRODUCTO' => 'Material resistente, diseño ergonómico.',
            'PRECIO' => 200.00,
            'CANTIDAD_VENDIDOS' => 80,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 60,
            'IMAGEN' => 'hartz-arenero.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 3,
            'COLORES_DISPONIBLES' => 'Gris',
            'TIPO_ENVIO' => 'express'
        ],
        [
            'MARCA' => 'Purina',
            'NOMBRE_PRODUCTO' => 'Croquetas para Gato Purina Cat Chow',
            'DESCRIPCION_PRODUCTO' => 'Croquetas para gato sabor pescado.',
            'CARACTERISTICAS_PRODUCTO' => 'Refuerza el sistema inmunológico, fácil digestión.',
            'PRECIO' => 250.00,
            'CANTIDAD_VENDIDOS' => 150,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 300,
            'IMAGEN' => 'purina-catchow.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 3,
            'COLORES_DISPONIBLES' => null,
            'TIPO_ENVIO' => 'internacional'
        ],

        // Celulares y Telefonía
        [
            'MARCA' => 'Apple',
            'NOMBRE_PRODUCTO' => 'iPhone 13 Pro Max',
            'DESCRIPCION_PRODUCTO' => 'Smartphone de alta gama con sistema iOS.',
            'CARACTERISTICAS_PRODUCTO' => 'Pantalla OLED, cámara de 12MP, 5G.',
            'PRECIO' => 26000.00,
            'CANTIDAD_VENDIDOS' => 400,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 10,
            'IMAGEN' => 'https://th.bing.com/th/id/R.6ed135b9f6dfbcb6eac062a97f47e847?rik=st4OJlqCmhZ%2f9w&pid=ImgRaw&r=0',
            'ID_VENDEDOR' => 4,
            'ID_CATEGORIA' => 8,
            'COLORES_DISPONIBLES' => 'Azul, Grafito',
            'TIPO_ENVIO' => 'express'
        ],
        [
            'MARCA' => 'Samsung',
            'NOMBRE_PRODUCTO' => 'Samsung Galaxy S22 Ultra',
            'DESCRIPCION_PRODUCTO' => 'Smartphone con pantalla infinita y cámara de alta calidad.',
            'CARACTERISTICAS_PRODUCTO' => 'Resolución de 108MP, batería de larga duración.',
            'PRECIO' => 23000.00,
            'CANTIDAD_VENDIDOS' => 300,
            'PRECIO_CON_DESCUENTO' => 21000.00,
            'PORCENTAJES_DESCUENTOS' => 8.7,
            'STOCK' => 15,
            'IMAGEN' => 'samsung-galaxy-s22.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 8,
            'COLORES_DISPONIBLES' => 'Negro, Blanco',
            'TIPO_ENVIO' => 'internacional'
        ],
        [
            'MARCA' => 'Motorola',
            'NOMBRE_PRODUCTO' => 'Motorola Edge 20 Pro',
            'DESCRIPCION_PRODUCTO' => 'Teléfono con pantalla OLED y cámara de 108MP.',
            'CARACTERISTICAS_PRODUCTO' => 'Tecnología de carga rápida, Android 11.',
            'PRECIO' => 12000.00,
            'CANTIDAD_VENDIDOS' => 250,
            'PRECIO_CON_DESCUENTO' => 10800.00,
            'PORCENTAJES_DESCUENTOS' => 10.0,
            'STOCK' => 25,
            'IMAGEN' => 'motorola-edge20.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 8,
            'COLORES_DISPONIBLES' => 'Negro, Azul',
            'TIPO_ENVIO' => 'express'
        ],
        [
            'MARCA' => 'Xiaomi',
            'NOMBRE_PRODUCTO' => 'Xiaomi Redmi Note 10',
            'DESCRIPCION_PRODUCTO' => 'Teléfono con batería de larga duración y cámara de 48MP.',
            'CARACTERISTICAS_PRODUCTO' => 'Pantalla AMOLED, carga rápida.',
            'PRECIO' => 8000.00,
            'CANTIDAD_VENDIDOS' => 500,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 50,
            'IMAGEN' => 'xiaomi-note10.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 8,
            'COLORES_DISPONIBLES' => 'Gris, Verde',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Huawei',
            'NOMBRE_PRODUCTO' => 'Huawei P40 Pro',
            'DESCRIPCION_PRODUCTO' => 'Smartphone con pantalla OLED y cámara Ultra Vision.',
            'CARACTERISTICAS_PRODUCTO' => 'Cámara de 50MP, conectividad 5G.',
            'PRECIO' => 15000.00,
            'CANTIDAD_VENDIDOS' => 150,
            'PRECIO_CON_DESCUENTO' => 13500.00,
            'PORCENTAJES_DESCUENTOS' => 10.0,
            'STOCK' => 20,
            'IMAGEN' => 'huawei-p40pro.jpg',
            'ID_VENDEDOR' => 4,
            'ID_CATEGORIA' => 8,
            'COLORES_DISPONIBLES' => 'Negro, Plata',
            'TIPO_ENVIO' => 'internacional'
        ],
        // Computación
        [
            'MARCA' => 'Dell',
            'NOMBRE_PRODUCTO' => 'Laptop Dell Inspiron 15',
            'DESCRIPCION_PRODUCTO' => 'Laptop con procesador Intel i5 y 8GB RAM.',
            'CARACTERISTICAS_PRODUCTO' => 'Pantalla Full HD, 256GB SSD.',
            'PRECIO' => 12000.00,
            'CANTIDAD_VENDIDOS' => 300,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 15,
            'IMAGEN' => 'dell-inspiron15.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 9,
            'COLORES_DISPONIBLES' => 'Negro',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'HP',
            'NOMBRE_PRODUCTO' => 'HP Pavilion x360',
            'DESCRIPCION_PRODUCTO' => 'Laptop convertible 2 en 1 con pantalla táctil.',
            'CARACTERISTICAS_PRODUCTO' => 'Procesador Intel i7, 16GB RAM, 512GB SSD.',
            'PRECIO' => 18000.00,
            'CANTIDAD_VENDIDOS' => 150,
            'PRECIO_CON_DESCUENTO' => 17000.00,
            'PORCENTAJES_DESCUENTOS' => 5.6,
            'STOCK' => 20,
            'IMAGEN' => 'hp-pavilion-x360.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 9,
            'COLORES_DISPONIBLES' => 'Plata',
            'TIPO_ENVIO' => 'express'
        ],
        [
            'MARCA' => 'Lenovo',
            'NOMBRE_PRODUCTO' => 'Lenovo IdeaPad 3',
            'DESCRIPCION_PRODUCTO' => 'Laptop ligera con pantalla de 15.6 pulgadas.',
            'CARACTERISTICAS_PRODUCTO' => 'AMD Ryzen 5, 8GB RAM, 512GB SSD.',
            'PRECIO' => 10000.00,
            'CANTIDAD_VENDIDOS' => 200,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 30,
            'IMAGEN' => 'lenovo-ideapad3.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 9,
            'COLORES_DISPONIBLES' => 'Negro',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Asus',
            'NOMBRE_PRODUCTO' => 'Asus ROG Zephyrus G14',
            'DESCRIPCION_PRODUCTO' => 'Laptop gamer con procesador Ryzen 9.',
            'CARACTERISTICAS_PRODUCTO' => '16GB RAM, 1TB SSD, GPU NVIDIA RTX 3060.',
            'PRECIO' => 35000.00,
            'CANTIDAD_VENDIDOS' => 80,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 10,
            'IMAGEN' => 'asus-rog-zephyrus-g14.jpg',
            'ID_VENDEDOR' => 4,
            'ID_CATEGORIA' => 9,
            'COLORES_DISPONIBLES' => 'Blanco',
            'TIPO_ENVIO' => 'internacional'
        ],
        [
            'MARCA' => 'Acer',
            'NOMBRE_PRODUCTO' => 'Acer Aspire 5',
            'DESCRIPCION_PRODUCTO' => 'Laptop de trabajo con buena relación precio/rendimiento.',
            'CARACTERISTICAS_PRODUCTO' => 'Intel Core i5, 8GB RAM, 1TB HDD.',
            'PRECIO' => 9000.00,
            'CANTIDAD_VENDIDOS' => 250,
            'PRECIO_CON_DESCUENTO' => 8500.00,
            'PORCENTAJES_DESCUENTOS' => 5.6,
            'STOCK' => 40,
            'IMAGEN' => 'acer-aspire5.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 9,
            'COLORES_DISPONIBLES' => 'Negro',
            'TIPO_ENVIO' => 'estándar'
        ],

        // Electrodomésticos
        [
            'MARCA' => 'Samsung',
            'NOMBRE_PRODUCTO' => 'Refrigerador Samsung 453L',
            'DESCRIPCION_PRODUCTO' => 'Refrigerador de 453 litros con tecnología de enfriamiento.',
            'CARACTERISTICAS_PRODUCTO' => 'Cajones de vegetales, sistema de ahorro energético.',
            'PRECIO' => 12000.00,
            'CANTIDAD_VENDIDOS' => 75,
            'PRECIO_CON_DESCUENTO' => 11000.00,
            'PORCENTAJES_DESCUENTOS' => 8.33,
            'STOCK' => 15,
            'IMAGEN' => 'samsung-refrigerador.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 10,
            'COLORES_DISPONIBLES' => 'Blanco',
            'TIPO_ENVIO' => 'express'
        ],
        [
            'MARCA' => 'LG',
            'NOMBRE_PRODUCTO' => 'Lavadora LG 10.5kg',
            'DESCRIPCION_PRODUCTO' => 'Lavadora de carga frontal con capacidad de 10.5 kg.',
            'CARACTERISTICAS_PRODUCTO' => 'Tecnología TurboWash, eficiente en energía.',
            'PRECIO' => 9000.00,
            'CANTIDAD_VENDIDOS' => 120,
            'PRECIO_CON_DESCUENTO' => 8500.00,
            'PORCENTAJES_DESCUENTOS' => 5.56,
            'STOCK' => 25,
            'IMAGEN' => 'lg-lavadora.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 10,
            'COLORES_DISPONIBLES' => 'Plata',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Whirlpool',
            'NOMBRE_PRODUCTO' => 'Horno de Microondas Whirlpool 20L',
            'DESCRIPCION_PRODUCTO' => 'Microondas compacto ideal para cocinas pequeñas.',
            'CARACTERISTICAS_PRODUCTO' => 'Funciones de descongelar y calentar.',
            'PRECIO' => 2000.00,
            'CANTIDAD_VENDIDOS' => 200,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 50,
            'IMAGEN' => 'whirlpool-microondas.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 10,
            'COLORES_DISPONIBLES' => 'Negro',
            'TIPO_ENVIO' => 'internacional'
        ],
        [
            'MARCA' => 'Oster',
            'NOMBRE_PRODUCTO' => 'Licuadora Oster 1.5L',
            'DESCRIPCION_PRODUCTO' => 'Licuadora con vaso de vidrio y múltiples velocidades.',
            'CARACTERISTICAS_PRODUCTO' => 'Ideal para smoothies y jugos.',
            'PRECIO' => 1200.00,
            'CANTIDAD_VENDIDOS' => 500,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 100,
            'IMAGEN' => 'oster-licuadora.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 10,
            'COLORES_DISPONIBLES' => 'Rojo',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Mabe',
            'NOMBRE_PRODUCTO' => 'Cafetera Mabe 12 Tazas',
            'DESCRIPCION_PRODUCTO' => 'Cafetera eléctrica para preparar hasta 12 tazas.',
            'CARACTERISTICAS_PRODUCTO' => 'Plato calefactor, apagado automático.',
            'PRECIO' => 800.00,
            'CANTIDAD_VENDIDOS' => 350,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 60,
            'IMAGEN' => 'mabe-cafetera.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 10,
            'COLORES_DISPONIBLES' => 'Negro',
            'TIPO_ENVIO' => 'estándar'
        ],

        // Electrónica, Audio y Video
        [
            'MARCA' => 'Sony',
            'NOMBRE_PRODUCTO' => 'Televisor Sony 55" 4K',
            'DESCRIPCION_PRODUCTO' => 'Televisor LED de 55 pulgadas con resolución 4K.',
            'CARACTERISTICAS_PRODUCTO' => 'Compatible con HDR y Smart TV.',
            'PRECIO' => 15000.00,
            'CANTIDAD_VENDIDOS' => 60,
            'PRECIO_CON_DESCUENTO' => 14000.00,
            'PORCENTAJES_DESCUENTOS' => 6.67,
            'STOCK' => 10,
            'IMAGEN' => 'sony-televisor.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 11,
            'COLORES_DISPONIBLES' => 'Negro',
            'TIPO_ENVIO' => 'express'
        ],
        [
            'MARCA' => 'Samsung',
            'NOMBRE_PRODUCTO' => 'Bocinas Samsung 2.1',
            'DESCRIPCION_PRODUCTO' => 'Sistema de sonido 2.1 canales.',
            'CARACTERISTICAS_PRODUCTO' => 'Subwoofer inalámbrico.',
            'PRECIO' => 5000.00,
            'CANTIDAD_VENDIDOS' => 80,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 25,
            'IMAGEN' => 'samsung-bocinas.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 11,
            'COLORES_DISPONIBLES' => 'Negro',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Apple',
            'NOMBRE_PRODUCTO' => 'iPhone 13 Pro 256GB',
            'DESCRIPCION_PRODUCTO' => 'Smartphone de última generación de Apple.',
            'CARACTERISTICAS_PRODUCTO' => 'Cámara triple, 256GB de almacenamiento.',
            'PRECIO' => 25000.00,
            'CANTIDAD_VENDIDOS' => 40,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 15,
            'IMAGEN' => 'iphone13pro.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 11,
            'COLORES_DISPONIBLES' => 'Oro, Plata, Grafito',
            'TIPO_ENVIO' => 'internacional'
        ],
        [
            'MARCA' => 'Xiaomi',
            'NOMBRE_PRODUCTO' => 'Xiaomi Mi 11',
            'DESCRIPCION_PRODUCTO' => 'Smartphone con pantalla AMOLED.',
            'CARACTERISTICAS_PRODUCTO' => '120Hz, cámara triple.',
            'PRECIO' => 12000.00,
            'CANTIDAD_VENDIDOS' => 60,
            'PRECIO_CON_DESCUENTO' => 11500.00,
            'PORCENTAJES_DESCUENTOS' => 4.17,
            'STOCK' => 20,
            'IMAGEN' => 'xiaomi-mi11.jpg',
            'ID_VENDEDOR' => 4,
            'ID_CATEGORIA' => 11,
            'COLORES_DISPONIBLES' => 'Negro, Azul',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'LG',
            'NOMBRE_PRODUCTO' => 'Auriculares LG TONE Free',
            'DESCRIPCION_PRODUCTO' => 'Auriculares inalámbricos con cancelación de ruido.',
            'CARACTERISTICAS_PRODUCTO' => 'Hasta 24 horas de batería.',
            'PRECIO' => 3000.00,
            'CANTIDAD_VENDIDOS' => 120,
            'PRECIO_CON_DESCUENTO' => 2800.00,
            'PORCENTAJES_DESCUENTOS' => 6.67,
            'STOCK' => 50,
            'IMAGEN' => 'lg-audifonos.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 11,
            'COLORES_DISPONIBLES' => 'Blanco',
            'TIPO_ENVIO' => 'estándar'
        ],

        // Joyas y Relojes
        [
            'MARCA' => 'Rolex',
            'NOMBRE_PRODUCTO' => 'Reloj Rolex Submariner',
            'DESCRIPCION_PRODUCTO' => 'Reloj de buceo icónico con movimiento automático.',
            'CARACTERISTICAS_PRODUCTO' => 'Resistencia al agua hasta 300m.',
            'PRECIO' => 50000.00,
            'CANTIDAD_VENDIDOS' => 10,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 5,
            'IMAGEN' => 'rolex-submariner.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 12,
            'COLORES_DISPONIBLES' => 'Negro',
            'TIPO_ENVIO' => 'internacional'
        ],
        [
            'MARCA' => 'Pandora',
            'NOMBRE_PRODUCTO' => 'Pulsera Pandora',
            'DESCRIPCION_PRODUCTO' => 'Pulsera de plata con charms intercambiables.',
            'CARACTERISTICAS_PRODUCTO' => 'Regalo perfecto para cualquier ocasión.',
            'PRECIO' => 3000.00,
            'CANTIDAD_VENDIDOS' => 50,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 30,
            'IMAGEN' => 'pandora-pulsera.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 12,
            'COLORES_DISPONIBLES' => 'Plata',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Guess',
            'NOMBRE_PRODUCTO' => 'Reloj Guess Mujer',
            'DESCRIPCION_PRODUCTO' => 'Reloj elegante para mujer.',
            'CARACTERISTICAS_PRODUCTO' => 'Diseño moderno y chic.',
            'PRECIO' => 4500.00,
            'CANTIDAD_VENDIDOS' => 30,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 20,
            'IMAGEN' => 'guess-reloj-mujer.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 12,
            'COLORES_DISPONIBLES' => 'Dorado',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Michael Kors',
            'NOMBRE_PRODUCTO' => 'Reloj Michael Kors',
            'DESCRIPCION_PRODUCTO' => 'Reloj de lujo con diseño exclusivo.',
            'CARACTERISTICAS_PRODUCTO' => 'Estilo elegante y sofisticado.',
            'PRECIO' => 8000.00,
            'CANTIDAD_VENDIDOS' => 20,
            'PRECIO_CON_DESCUENTO' => 7600.00,
            'PORCENTAJES_DESCUENTOS' => 5,
            'STOCK' => 10,
            'IMAGEN' => 'michael-kors-reloj.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 12,
            'COLORES_DISPONIBLES' => 'Plata, Rosa',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Tiffany & Co.',
            'NOMBRE_PRODUCTO' => 'Collar Tiffany',
            'DESCRIPCION_PRODUCTO' => 'Collar de plata con corazón Tiffany.',
            'CARACTERISTICAS_PRODUCTO' => 'Ideal para ocasiones especiales.',
            'PRECIO' => 12000.00,
            'CANTIDAD_VENDIDOS' => 15,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 8,
            'IMAGEN' => 'tiffany-collar.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 12,
            'COLORES_DISPONIBLES' => 'Plata',
            'TIPO_ENVIO' => 'internacional'
        ],

        // Ropa
        [
            'MARCA' => 'Nike',
            'NOMBRE_PRODUCTO' => 'Zapatillas Nike Air Max',
            'DESCRIPCION_PRODUCTO' => 'Zapatillas deportivas para hombre.',
            'CARACTERISTICAS_PRODUCTO' => 'Comodidad y estilo.',
            'PRECIO' => 3500.00,
            'CANTIDAD_VENDIDOS' => 100,
            'PRECIO_CON_DESCUENTO' => 3200.00,
            'PORCENTAJES_DESCUENTOS' => 8.57,
            'STOCK' => 40,
            'IMAGEN' => 'nike-air-max.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 13,
            'COLORES_DISPONIBLES' => 'Negro, Blanco',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Adidas',
            'NOMBRE_PRODUCTO' => 'Camisa Adidas Climalite',
            'DESCRIPCION_PRODUCTO' => 'Camisa deportiva para entrenamiento.',
            'CARACTERISTICAS_PRODUCTO' => 'Transpirable y ligera.',
            'PRECIO' => 1200.00,
            'CANTIDAD_VENDIDOS' => 80,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 50,
            'IMAGEN' => 'adidas-camisa.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 13,
            'COLORES_DISPONIBLES' => 'Azul',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Levi\'s',
            'NOMBRE_PRODUCTO' => 'Jeans Levi\'s 501',
            'DESCRIPCION_PRODUCTO' => 'Jeans clásicos para hombre.',
            'CARACTERISTICAS_PRODUCTO' => 'Estilo atemporal y versátil.',
            'PRECIO' => 2500.00,
            'CANTIDAD_VENDIDOS' => 60,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 30,
            'IMAGEN' => 'levis-jeans.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 13,
            'COLORES_DISPONIBLES' => 'Azul',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Puma',
            'NOMBRE_PRODUCTO' => 'Sudadera Puma',
            'DESCRIPCION_PRODUCTO' => 'Sudadera de entrenamiento con capucha.',
            'CARACTERISTICAS_PRODUCTO' => 'Comodidad y estilo urbano.',
            'PRECIO' => 1500.00,
            'CANTIDAD_VENDIDOS' => 90,
            'PRECIO_CON_DESCUENTO' => 1400.00,
            'PORCENTAJES_DESCUENTOS' => 6.67,
            'STOCK' => 40,
            'IMAGEN' => 'puma-sudadera.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 13,
            'COLORES_DISPONIBLES' => 'Negro, Gris',
            'TIPO_ENVIO' => 'estándar'
        ],
        [
            'MARCA' => 'Zara',
            'NOMBRE_PRODUCTO' => 'Vestido de Zara',
            'DESCRIPCION_PRODUCTO' => 'Vestido elegante para ocasiones especiales.',
            'CARACTERISTICAS_PRODUCTO' => 'Diseño moderno y chic.',
            'PRECIO' => 2500.00,
            'CANTIDAD_VENDIDOS' => 20,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 15,
            'IMAGEN' => 'zara-vestido.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 13,
            'COLORES_DISPONIBLES' => 'Rojo, Negro',
            'TIPO_ENVIO' => 'estándar'
        ],

            // Juegos y Juguetes
            [
            'MARCA' => 'Lego',
            'NOMBRE_PRODUCTO' => 'Set de Lego Star Wars',
            'DESCRIPCION_PRODUCTO' => 'Set de construcción de Star Wars con figuras.',
            'CARACTERISTICAS_PRODUCTO' => 'Incluye 5 figuras y piezas adicionales.',
            'PRECIO' => 1500.00,
            'CANTIDAD_VENDIDOS' => 75,
            'PRECIO_CON_DESCUENTO' => 1400.00,
            'PORCENTAJES_DESCUENTOS' => 6.67,
            'STOCK' => 20,
            'IMAGEN' => 'lego-star-wars.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 14,
            'COLORES_DISPONIBLES' => 'Multicolor',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Mattel',
            'NOMBRE_PRODUCTO' => 'Muñeca Barbie',
            'DESCRIPCION_PRODUCTO' => 'Muñeca Barbie con accesorios y ropa.',
            'CARACTERISTICAS_PRODUCTO' => 'Incluye ropa adicional y complementos.',
            'PRECIO' => 600.00,
            'CANTIDAD_VENDIDOS' => 120,
            'PRECIO_CON_DESCUENTO' => 550.00,
            'PORCENTAJES_DESCUENTOS' => 8.33,
            'STOCK' => 50,
            'IMAGEN' => 'barbie-muneca.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 14,
            'COLORES_DISPONIBLES' => 'Multicolor',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Hasbro',
            'NOMBRE_PRODUCTO' => 'Juego de Monopoly',
            'DESCRIPCION_PRODUCTO' => 'Juego de mesa Monopoly clásico.',
            'CARACTERISTICAS_PRODUCTO' => 'Para 2 a 6 jugadores.',
            'PRECIO' => 800.00,
            'CANTIDAD_VENDIDOS' => 90,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 40,
            'IMAGEN' => 'monopoly.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 14,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Nerf',
            'NOMBRE_PRODUCTO' => 'Blaster Nerf Elite',
            'DESCRIPCION_PRODUCTO' => 'Blaster de dardos Nerf con 10 dardos.',
            'CARACTERISTICAS_PRODUCTO' => 'Rango de tiro de hasta 27 metros.',
            'PRECIO' => 1000.00,
            'CANTIDAD_VENDIDOS' => 60,
            'PRECIO_CON_DESCUENTO' => 950.00,
            'PORCENTAJES_DESCUENTOS' => 5,
            'STOCK' => 30,
            'IMAGEN' => 'nerf-blaster.jpg',
            'ID_VENDEDOR' => 4,
            'ID_CATEGORIA' => 14,
            'COLORES_DISPONIBLES' => 'Naranja',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Fisher-Price',
            'NOMBRE_PRODUCTO' => 'Juguete de Bloques para Apilar',
            'DESCRIPCION_PRODUCTO' => 'Bloques de colores para apilar y aprender.',
            'CARACTERISTICAS_PRODUCTO' => 'Desarrolla habilidades motoras.',
            'PRECIO' => 450.00,
            'CANTIDAD_VENDIDOS' => 110,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 80,
            'IMAGEN' => 'bloques-fisher-price.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 14,
            'COLORES_DISPONIBLES' => 'Multicolor',
            'TIPO_ENVIO' => 'estándar'
            ],

            // Libros, Revistas y Comics
            [
            'MARCA' => 'Penguin',
            'NOMBRE_PRODUCTO' => 'El Gran Gatsby',
            'DESCRIPCION_PRODUCTO' => 'Novela clásica de F. Scott Fitzgerald.',
            'CARACTERISTICAS_PRODUCTO' => 'Versión de tapa blanda.',
            'PRECIO' => 300.00,
            'CANTIDAD_VENDIDOS' => 50,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 20,
            'IMAGEN' => 'gran-gatsby.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 15,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'HarperCollins',
            'NOMBRE_PRODUCTO' => '1984',
            'DESCRIPCION_PRODUCTO' => 'Novela distópica de George Orwell.',
            'CARACTERISTICAS_PRODUCTO' => 'Edición de bolsillo.',
            'PRECIO' => 350.00,
            'CANTIDAD_VENDIDOS' => 60,
            'PRECIO_CON_DESCUENTO' => 330.00,
            'PORCENTAJES_DESCUENTOS' => 5.71,
            'STOCK' => 25,
            'IMAGEN' => '1984.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 15,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Marvel',
            'NOMBRE_PRODUCTO' => 'Spider-Man: Homecoming',
            'DESCRIPCION_PRODUCTO' => 'Comic de Spider-Man con aventuras emocionantes.',
            'CARACTERISTICAS_PRODUCTO' => 'Incluye ilustraciones a todo color.',
            'PRECIO' => 250.00,
            'CANTIDAD_VENDIDOS' => 100,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 50,
            'IMAGEN' => 'spiderman-comic.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 15,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Random House',
            'NOMBRE_PRODUCTO' => 'Sapiens: De animales a dioses',
            'DESCRIPCION_PRODUCTO' => 'Historia breve de la humanidad.',
            'CARACTERISTICAS_PRODUCTO' => 'Explora la evolución de nuestra especie.',
            'PRECIO' => 400.00,
            'CANTIDAD_VENDIDOS' => 30,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 15,
            'IMAGEN' => 'sapiens.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 15,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Galdós',
            'NOMBRE_PRODUCTO' => 'Fortunata y Jacinta',
            'DESCRIPCION_PRODUCTO' => 'Obra maestra de Benito Pérez Galdós.',
            'CARACTERISTICAS_PRODUCTO' => 'Narrativa profunda y conmovedora.',
            'PRECIO' => 450.00,
            'CANTIDAD_VENDIDOS' => 20,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 10,
            'IMAGEN' => 'fortunata-jacinta.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 15,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],

            // Música, Películas y Series
            [
            'MARCA' => 'Sony',
            'NOMBRE_PRODUCTO' => 'Álbum de Música: Thriller',
            'DESCRIPCION_PRODUCTO' => 'Álbum clásico de Michael Jackson.',
            'CARACTERISTICAS_PRODUCTO' => 'Versión remasterizada.',
            'PRECIO' => 300.00,
            'CANTIDAD_VENDIDOS' => 80,
            'PRECIO_CON_DESCUENTO' => 280.00,
            'PORCENTAJES_DESCUENTOS' => 6.67,
            'STOCK' => 40,
            'IMAGEN' => 'thriller.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 16,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Warner Bros',
            'NOMBRE_PRODUCTO' => 'Película: Inception',
            'DESCRIPCION_PRODUCTO' => 'Película de ciencia ficción dirigida por Christopher Nolan.',
            'CARACTERISTICAS_PRODUCTO' => 'Edición Blu-ray.',
            'PRECIO' => 500.00,
            'CANTIDAD_VENDIDOS' => 60,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 30,
            'IMAGEN' => 'inception.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 16,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Netflix',
            'NOMBRE_PRODUCTO' => 'Serie: Stranger Things - Temporada 1',
            'DESCRIPCION_PRODUCTO' => 'Temporada completa de la popular serie.',
            'CARACTERISTICAS_PRODUCTO' => 'Incluye todos los episodios.',
            'PRECIO' => 400.00,
            'CANTIDAD_VENDIDOS' => 50,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 25,
            'IMAGEN' => 'stranger-things.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 16,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Disney',
            'NOMBRE_PRODUCTO' => 'Película: Moana',
            'DESCRIPCION_PRODUCTO' => 'Película animada de Disney.',
            'CARACTERISTICAS_PRODUCTO' => 'Versión en Blu-ray.',
            'PRECIO' => 300.00,
            'CANTIDAD_VENDIDOS' => 90,
            'PRECIO_CON_DESCUENTO' => 250.00,
            'PORCENTAJES_DESCUENTOS' => 16.67,
            'STOCK' => 50,
            'IMAGEN' => 'moana.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 16,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Universal',
            'NOMBRE_PRODUCTO' => 'Película: Jurassic Park',
            'DESCRIPCION_PRODUCTO' => 'Clásica película de ciencia ficción.',
            'CARACTERISTICAS_PRODUCTO' => 'Edición especial.',
            'PRECIO' => 400.00,
            'CANTIDAD_VENDIDOS' => 20,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 15,
            'IMAGEN' => 'jurassic-park.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 16,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],

            // Recuerdos, Cotillón y Fiestas
            [
            'MARCA' => 'Party City',
            'NOMBRE_PRODUCTO' => 'Decoración de Cumpleaños - Kit de Fiesta',
            'DESCRIPCION_PRODUCTO' => 'Kit completo de decoración para fiestas de cumpleaños.',
            'CARACTERISTICAS_PRODUCTO' => 'Incluye globos, pancartas y confeti.',
            'PRECIO' => 500.00,
            'CANTIDAD_VENDIDOS' => 100,
            'PRECIO_CON_DESCUENTO' => 450.00,
            'PORCENTAJES_DESCUENTOS' => 10,
            'STOCK' => 30,
            'IMAGEN' => 'kit-fiesta.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 17,
            'COLORES_DISPONIBLES' => 'Multicolor',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Bolsas de Papel',
            'NOMBRE_PRODUCTO' => 'Bolsas de Regalo - Pack de 10',
            'DESCRIPCION_PRODUCTO' => 'Bolsas de regalo de papel kraft.',
            'CARACTERISTICAS_PRODUCTO' => 'Tamaño mediano, ideal para regalos.',
            'PRECIO' => 200.00,
            'CANTIDAD_VENDIDOS' => 50,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 40,
            'IMAGEN' => 'bolsas-regalo.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 17,
            'COLORES_DISPONIBLES' => 'Kraft',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Amscan',
            'NOMBRE_PRODUCTO' => 'Piñata de Unicornio',
            'DESCRIPCION_PRODUCTO' => 'Piñata decorativa para fiestas.',
            'CARACTERISTICAS_PRODUCTO' => 'Incluye confeti y caramelos.',
            'PRECIO' => 350.00,
            'CANTIDAD_VENDIDOS' => 70,
            'PRECIO_CON_DESCUENTO' => 330.00,
            'PORCENTAJES_DESCUENTOS' => 5.71,
            'STOCK' => 25,
            'IMAGEN' => 'pinata-unicornio.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 17,
            'COLORES_DISPONIBLES' => 'Multicolor',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Wilton',
            'NOMBRE_PRODUCTO' => 'Kit de Decoración de Pasteles',
            'DESCRIPCION_PRODUCTO' => 'Kit completo para decorar pasteles.',
            'CARACTERISTICAS_PRODUCTO' => 'Incluye boquillas, mangas y recetas.',
            'PRECIO' => 600.00,
            'CANTIDAD_VENDIDOS' => 40,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 15,
            'IMAGEN' => 'kit-decoracion-pasteles.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 17,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Hallmark',
            'NOMBRE_PRODUCTO' => 'Tarjetas de Felicitación - Pack de 12',
            'DESCRIPCION_PRODUCTO' => 'Tarjetas de felicitación para diversas ocasiones.',
            'CARACTERISTICAS_PRODUCTO' => 'Diseños coloridos y emotivos.',
            'PRECIO' => 250.00,
            'CANTIDAD_VENDIDOS' => 90,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 50,
            'IMAGEN' => 'tarjetas-felicitacion.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 17,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],

            // Ropa
            [
            'MARCA' => 'Nike',
            'NOMBRE_PRODUCTO' => 'Zapatillas de Running',
            'DESCRIPCION_PRODUCTO' => 'Zapatillas ligeras y cómodas para correr.',
            'CARACTERISTICAS_PRODUCTO' => 'Diseño transpirable y soporte adicional.',
            'PRECIO' => 1200.00,
            'CANTIDAD_VENDIDOS' => 200,
            'PRECIO_CON_DESCUENTO' => 1100.00,
            'PORCENTAJES_DESCUENTOS' => 8.33,
            'STOCK' => 60,
            'IMAGEN' => 'zapatillas-nike.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 18,
            'COLORES_DISPONIBLES' => 'Negro, Blanco',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Adidas',
            'NOMBRE_PRODUCTO' => 'Camiseta Deportiva',
            'DESCRIPCION_PRODUCTO' => 'Camiseta ligera y cómoda para actividades deportivas.',
            'CARACTERISTICAS_PRODUCTO' => 'Tejido que absorbe la humedad.',
            'PRECIO' => 500.00,
            'CANTIDAD_VENDIDOS' => 150,
            'PRECIO_CON_DESCUENTO' => 450.00,
            'PORCENTAJES_DESCUENTOS' => 10,
            'STOCK' => 80,
            'IMAGEN' => 'camiseta-adidas.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 18,
            'COLORES_DISPONIBLES' => 'Azul, Verde',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Levi\'s',
            'NOMBRE_PRODUCTO' => 'Jeans Clásicos',
            'DESCRIPCION_PRODUCTO' => 'Jeans de corte recto, cómodo y versátil.',
            'CARACTERISTICAS_PRODUCTO' => 'Hechos de algodón, varios tamaños disponibles.',
            'PRECIO' => 800.00,
            'CANTIDAD_VENDIDOS' => 100,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 50,
            'IMAGEN' => 'jeans-levis.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 18,
            'COLORES_DISPONIBLES' => 'Azul, Negro',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Zara',
            'NOMBRE_PRODUCTO' => 'Chaqueta de Invierno',
            'DESCRIPCION_PRODUCTO' => 'Chaqueta abrigadora para invierno.',
            'CARACTERISTICAS_PRODUCTO' => 'Impermeable y cortaviento.',
            'PRECIO' => 1500.00,
            'CANTIDAD_VENDIDOS' => 80,
            'PRECIO_CON_DESCUENTO' => 1300.00,
            'PORCENTAJES_DESCUENTOS' => 13.33,
            'STOCK' => 30,
            'IMAGEN' => 'chaqueta-zara.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 18,
            'COLORES_DISPONIBLES' => 'Negro, Verde',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'H&M',
            'NOMBRE_PRODUCTO' => 'Vestido de Verano',
            'DESCRIPCION_PRODUCTO' => 'Vestido ligero y fresco para el verano.',
            'CARACTERISTICAS_PRODUCTO' => 'Ideal para ocasiones informales.',
            'PRECIO' => 600.00,
            'CANTIDAD_VENDIDOS' => 200,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 100,
            'IMAGEN' => 'vestido-verano.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 18,
            'COLORES_DISPONIBLES' => 'Rosa, Blanco',
            'TIPO_ENVIO' => 'estándar'
            ],

            // Bolsas y Calzado
            [
            'MARCA' => 'Gucci',
            'NOMBRE_PRODUCTO' => 'Bolso de Mano',
            'DESCRIPCION_PRODUCTO' => 'Bolso de lujo, ideal para ocasiones especiales.',
            'CARACTERISTICAS_PRODUCTO' => 'Diseño exclusivo, hecho a mano.',
            'PRECIO' => 3000.00,
            'CANTIDAD_VENDIDOS' => 30,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 15,
            'IMAGEN' => 'bolso-gucci.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 19,
            'COLORES_DISPONIBLES' => 'Negro, Marrón',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Nike',
            'NOMBRE_PRODUCTO' => 'Zapatillas Deportivas',
            'DESCRIPCION_PRODUCTO' => 'Zapatillas cómodas para entrenamiento y uso diario.',
            'CARACTERISTICAS_PRODUCTO' => 'Amortiguación y soporte.',
            'PRECIO' => 900.00,
            'CANTIDAD_VENDIDOS' => 150,
            'PRECIO_CON_DESCUENTO' => 800.00,
            'PORCENTAJES_DESCUENTOS' => 11.11,
            'STOCK' => 100,
            'IMAGEN' => 'zapatillas-nike-deportivas.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 19,
            'COLORES_DISPONIBLES' => 'Blanco, Azul',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Adidas',
            'NOMBRE_PRODUCTO' => 'Mochila Deportiva',
            'DESCRIPCION_PRODUCTO' => 'Mochila ideal para el gimnasio y actividades al aire libre.',
            'CARACTERISTICAS_PRODUCTO' => 'Bolsillos múltiples, resistente al agua.',
            'PRECIO' => 500.00,
            'CANTIDAD_VENDIDOS' => 80,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 50,
            'IMAGEN' => 'mochila-adidas.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 19,
            'COLORES_DISPONIBLES' => 'Negro, Rojo',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Fossil',
            'NOMBRE_PRODUCTO' => 'Reloj de Pulsera',
            'DESCRIPCION_PRODUCTO' => 'Reloj de lujo con correa de cuero.',
            'CARACTERISTICAS_PRODUCTO' => 'Resistente al agua, diseño elegante.',
            'PRECIO' => 1500.00,
            'CANTIDAD_VENDIDOS' => 50,
            'PRECIO_CON_DESCUENTO' => 1200.00,
            'PORCENTAJES_DESCUENTOS' => 20,
            'STOCK' => 30,
            'IMAGEN' => 'reloj-fossil.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 19,
            'COLORES_DISPONIBLES' => 'Negro, Marrón',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Vans',
            'NOMBRE_PRODUCTO' => 'Zapatillas de Lona',
            'DESCRIPCION_PRODUCTO' => 'Zapatillas de lona ideales para uso diario.',
            'CARACTERISTICAS_PRODUCTO' => 'Estilo clásico, cómodas.',
            'PRECIO' => 700.00,
            'CANTIDAD_VENDIDOS' => 90,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 40,
            'IMAGEN' => 'zapatillas-vans.jpg',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 19,
            'COLORES_DISPONIBLES' => 'Blanco, Negro',
            'TIPO_ENVIO' => 'estándar'
            ],

            // Salud y Equipamiento Médico
            [
            'MARCA' => 'Philips',
            'NOMBRE_PRODUCTO' => 'Termómetro Digital',
            'DESCRIPCION_PRODUCTO' => 'Termómetro digital para medición rápida.',
            'CARACTERISTICAS_PRODUCTO' => 'Precisión rápida, adecuado para adultos y niños.',
            'PRECIO' => 300.00,
            'CANTIDAD_VENDIDOS' => 100,
            'PRECIO_CON_DESCUENTO' => 250.00,
            'PORCENTAJES_DESCUENTOS' => 16.67,
            'STOCK' => 50,
            'IMAGEN' => 'termometro-philips.jpg',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 20,
            'COLORES_DISPONIBLES' => 'Blanco',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Braun',
            'NOMBRE_PRODUCTO' => 'Afeitadora Eléctrica',
            'DESCRIPCION_PRODUCTO' => 'Afeitadora eléctrica para un afeitado cómodo.',
            'CARACTERISTICAS_PRODUCTO' => 'Diseño ergonómico y resistente al agua.',
            'PRECIO' => 800.00,
            'CANTIDAD_VENDIDOS' => 50,
            'PRECIO_CON_DESCUENTO' => 750.00,
            'PORCENTAJES_DESCUENTOS' => 6.25,
            'STOCK' => 30,
            'IMAGEN' => 'afeitadora-braun.jpg',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 20,
            'COLORES_DISPONIBLES' => 'Negro, Azul',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Fitbit',
            'NOMBRE_PRODUCTO' => 'Reloj Inteligente',
            'DESCRIPCION_PRODUCTO' => 'Reloj inteligente con monitoreo de salud.',
            'CARACTERISTICAS_PRODUCTO' => 'Seguimiento de actividad, monitoreo de sueño.',
            'PRECIO' => 1500.00,
            'CANTIDAD_VENDIDOS' => 70,
            'PRECIO_CON_DESCUENTO' => 1300.00,
            'PORCENTAJES_DESCUENTOS' => 13.33,
            'STOCK' => 40,
            'IMAGEN' => 'https://th.bing.com/th/id/R.6ed135b9f6dfbcb6eac062a97f47e847?rik=st4OJlqCmhZ%2f9w&pid=ImgRaw&r=0',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 20,
            'COLORES_DISPONIBLES' => 'Negro, Rosa',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Tensoval',
            'NOMBRE_PRODUCTO' => 'Esfingomanómetro Digital',
            'DESCRIPCION_PRODUCTO' => 'Dispositivo para medir la presión arterial.',
            'CARACTERISTICAS_PRODUCTO' => 'Con pantalla grande y fácil de usar.',
            'PRECIO' => 500.00,
            'CANTIDAD_VENDIDOS' => 80,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 50,
            'IMAGEN' => 'https://th.bing.com/th/id/R.6ed135b9f6dfbcb6eac062a97f47e847?rik=st4OJlqCmhZ%2f9w&pid=ImgRaw&r=0',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 20,
            'COLORES_DISPONIBLES' => 'Blanco',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Nestle',
            'NOMBRE_PRODUCTO' => 'Leche En Polvo Nutricional',
            'DESCRIPCION_PRODUCTO' => 'Leche en polvo para una alimentación balanceada.',
            'CARACTERISTICAS_PRODUCTO' => 'Fórmula rica en nutrientes.',
            'PRECIO' => 400.00,
            'CANTIDAD_VENDIDOS' => 90,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 60,
            'IMAGEN' => 'https://th.bing.com/th/id/R.6ed135b9f6dfbcb6eac062a97f47e847?rik=st4OJlqCmhZ%2f9w&pid=ImgRaw&r=0',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 20,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],

            // Servicios
            [
            'MARCA' => 'Freelance',
            'NOMBRE_PRODUCTO' => 'Servicio de Diseño Gráfico',
            'DESCRIPCION_PRODUCTO' => 'Diseño gráfico para empresas y particulares.',
            'CARACTERISTICAS_PRODUCTO' => 'Logos, tarjetas de presentación, folletos.',
            'PRECIO' => 1500.00,
            'CANTIDAD_VENDIDOS' => 20,
            'PRECIO_CON_DESCUENTO' => 1400.00,
            'PORCENTAJES_DESCUENTOS' => 6.67,
            'STOCK' => 10,
            'IMAGEN' => 'https://th.bing.com/th/id/R.6ed135b9f6dfbcb6eac062a97f47e847?rik=st4OJlqCmhZ%2f9w&pid=ImgRaw&r=0',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 21,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Tutoría',
            'NOMBRE_PRODUCTO' => 'Clases de Matemáticas en Línea',
            'DESCRIPCION_PRODUCTO' => 'Clases particulares de matemáticas para todos los niveles.',
            'CARACTERISTICAS_PRODUCTO' => 'Aprendizaje personalizado, horario flexible.',
            'PRECIO' => 300.00,
            'CANTIDAD_VENDIDOS' => 50,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 25,
            'IMAGEN' => 'https://th.bing.com/th/id/R.6ed135b9f6dfbcb6eac062a97f47e847?rik=st4OJlqCmhZ%2f9w&pid=ImgRaw&r=0',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 21,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Turismo',
            'NOMBRE_PRODUCTO' => 'Paquete Turístico a la Playa',
            'DESCRIPCION_PRODUCTO' => 'Todo incluido para unas vacaciones inolvidables.',
            'CARACTERISTICAS_PRODUCTO' => 'Alojamiento, comidas y actividades.',
            'PRECIO' => 5000.00,
            'CANTIDAD_VENDIDOS' => 15,
            'PRECIO_CON_DESCUENTO' => 4500.00,
            'PORCENTAJES_DESCUENTOS' => 10,
            'STOCK' => 5,
            'IMAGEN' => 'https://th.bing.com/th/id/R.6ed135b9f6dfbcb6eac062a97f47e847?rik=st4OJlqCmhZ%2f9w&pid=ImgRaw&r=0',
            'ID_VENDEDOR' => 3,
            'ID_CATEGORIA' => 21,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Limpieza',
            'NOMBRE_PRODUCTO' => 'Servicio de Limpieza a Domicilio',
            'DESCRIPCION_PRODUCTO' => 'Limpieza profunda de hogares y oficinas.',
            'CARACTERISTICAS_PRODUCTO' => 'Personal calificado y materiales incluidos.',
            'PRECIO' => 800.00,
            'CANTIDAD_VENDIDOS' => 10,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 8,
            'IMAGEN' => 'https://th.bing.com/th/id/R.6ed135b9f6dfbcb6eac062a97f47e847?rik=st4OJlqCmhZ%2f9w&pid=ImgRaw&r=0',
            'ID_VENDEDOR' => 2,
            'ID_CATEGORIA' => 21,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
            [
            'MARCA' => 'Clases de Idiomas',
            'NOMBRE_PRODUCTO' => 'Curso de Inglés en Línea',
            'DESCRIPCION_PRODUCTO' => 'Clases de inglés para principiantes y avanzados.',
            'CARACTERISTICAS_PRODUCTO' => 'Aprendizaje interactivo y personalizado.',
            'PRECIO' => 600.00,
            'CANTIDAD_VENDIDOS' => 30,
            'PRECIO_CON_DESCUENTO' => null,
            'PORCENTAJES_DESCUENTOS' => null,
            'STOCK' => 20,
            'IMAGEN' => 'https://th.bing.com/th/id/R.6ed135b9f6dfbcb6eac062a97f47e847?rik=st4OJlqCmhZ%2f9w&pid=ImgRaw&r=0',
            'ID_VENDEDOR' => 1,
            'ID_CATEGORIA' => 21,
            'COLORES_DISPONIBLES' => 'N/A',
            'TIPO_ENVIO' => 'estándar'
            ],
        ]);
    }
}
