<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('PRODUCTOS')->insert([
            // Belleza y Cuidado Personal
            [
                'MARCA' => 'Nivea',
                'NOMBRE_PRODUCTO' => 'Crema Corporal Nivea Soft',
                'DESCRIPCION_PRODUCTO' => 'Crema hidratante para piel seca.',
                'CARACTERISTICAS_PRODUCTO' => 'Hidratación profunda, rápida absorción.',
                'PRECIO' => 150.00,
                'CANTIDAD_VENDIDOS' => 350,
                'PRECIO_CON_DESCUENTO' => 120.00,
                'PORCENTAJES_DESCUENTOS' => 20.0,
                'STOCK' => 200,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/loreal-shampoo.jpg',
                'ID_VENDEDOR' => 1,
                'ID_CATEGORIA' => 1,
                'COLORES_DISPONIBLES' => 'Blanco',
                'TIPO_ENVIO' => 'estándar',
                'FECHA_ENTREGA' => '2024-12-01',
                'COSTE_ENTREGA' => 10.00,
                'CALIFICACION' => 4.7,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Hidratación intensa, rápida absorción.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'MARCA' => 'L Oréal',
                'NOMBRE_PRODUCTO' => 'Shampoo L’Oréal Paris',
                'DESCRIPCION_PRODUCTO' => 'Shampoo revitalizante para cabellos secos.',
                'CARACTERISTICAS_PRODUCTO' => 'Fortalece y revitaliza.',
                'PRECIO' => 90.00,
                'CANTIDAD_VENDIDOS' => 500,
                'PRECIO_CON_DESCUENTO' => 80.00,
                'PORCENTAJES_DESCUENTOS' => 11.1,
                'STOCK' => 300,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/nivea-soft.jpg',
                'ID_VENDEDOR' => 2,
                'ID_CATEGORIA' => 1,
                'COLORES_DISPONIBLES' => 'Transparente',
                'TIPO_ENVIO' => 'express',
                'FECHA_ENTREGA' => '2024-12-05',
                'COSTE_ENTREGA' => 15.00,
                'CALIFICACION' => 4.3,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Hidratación y fortalecimiento.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // Accesorios para autos
            [
                'MARCA' => 'Michelin',
                'NOMBRE_PRODUCTO' => 'Juego de Neumáticos Michelin',
                'DESCRIPCION_PRODUCTO' => 'Neumáticos de alta durabilidad para autos de uso diario.',
                'CARACTERISTICAS_PRODUCTO' => 'Alta resistencia, larga duración.',
                'PRECIO' => 1250.00,
                'CANTIDAD_VENDIDOS' => 100,
                'PRECIO_CON_DESCUENTO' => 230.00,
                'PORCENTAJES_DESCUENTOS' => 8.0,
                'STOCK' => 50,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Neumaticos+Michelin.jpg',
                'ID_VENDEDOR' => 3,
                'ID_CATEGORIA' => 2,
                'COLORES_DISPONIBLES' => 'Negro',
                'TIPO_ENVIO' => 'internacional',
                'FECHA_ENTREGA' => '2024-12-10',
                'COSTE_ENTREGA' => 30.00,
                'CALIFICACION' => 4.8,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Neumáticos de alta calidad para todo tipo de terreno.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // Agro
            [
                'MARCA' => 'Bayer',
                'NOMBRE_PRODUCTO' => 'Fungicida Bayer',
                'DESCRIPCION_PRODUCTO' => 'Fungicida para el control de enfermedades en cultivos.',
                'CARACTERISTICAS_PRODUCTO' => 'Previene hongos, fácil aplicación.',
                'PRECIO' => 500.00,
                'CANTIDAD_VENDIDOS' => 80,
                'PRECIO_CON_DESCUENTO' => 450.00,
                'PORCENTAJES_DESCUENTOS' => 10.0,
                'STOCK' => 50,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Fungicida+Bayer.jpg',
                'ID_VENDEDOR' => 7,
                'ID_CATEGORIA' => 4,
                'COLORES_DISPONIBLES' => 'Verde',
                'TIPO_ENVIO' => 'estándar',
                'FECHA_ENTREGA' => '2024-12-15',
                'COSTE_ENTREGA' => 20.00,
                'CALIFICACION' => 4.6,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Controla enfermedades fungosas en cultivos.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'MARCA' => 'Monsanto',
                'NOMBRE_PRODUCTO' => 'Herbicida Monsanto',
                'DESCRIPCION_PRODUCTO' => 'Herbicida para control de maleza.',
                'CARACTERISTICAS_PRODUCTO' => 'Destruye maleza de forma efectiva.',
                'PRECIO' => 350.00,
                'CANTIDAD_VENDIDOS' => 120,
                'PRECIO_CON_DESCUENTO' => 310.00,
                'PORCENTAJES_DESCUENTOS' => 11.4,
                'STOCK' => 100,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Herbicida+Monsanto.jpg',
                'ID_VENDEDOR' => 8,
                'ID_CATEGORIA' => 4,
                'COLORES_DISPONIBLES' => 'Amarillo',
                'TIPO_ENVIO' => 'internacional',
                'FECHA_ENTREGA' => '2024-12-17',
                'COSTE_ENTREGA' => 30.00,
                'CALIFICACION' => 4.5,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Eficaz contra todo tipo de maleza.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // Alimentos y Bebidas
            [
                'MARCA' => 'Coca-Cola',
                'NOMBRE_PRODUCTO' => 'Coca-Cola 500ml',
                'DESCRIPCION_PRODUCTO' => 'Refresco carbonatado sabor cola.',
                'CARACTERISTICAS_PRODUCTO' => 'Refresco clásico con gas.',
                'PRECIO' => 20.00,
                'CANTIDAD_VENDIDOS' => 2000,
                'PRECIO_CON_DESCUENTO' => 18.00,
                'PORCENTAJES_DESCUENTOS' => 10.0,
                'STOCK' => 500,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Coca-Cola+500ml.jpg',
                'ID_VENDEDOR' => 9,
                'ID_CATEGORIA' => 5,
                'COLORES_DISPONIBLES' => 'Rojo',
                'TIPO_ENVIO' => 'estándar',
                'FECHA_ENTREGA' => '2024-12-01',
                'COSTE_ENTREGA' => 5.00,
                'CALIFICACION' => 4.8,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Bebida refrescante, ideal para todo momento.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'MARCA' => 'Nestlé',
                'NOMBRE_PRODUCTO' => 'Cereal Nestlé',
                'DESCRIPCION_PRODUCTO' => 'Cereal nutritivo para el desayuno.',
                'CARACTERISTICAS_PRODUCTO' => 'Rico en fibra y vitaminas.',
                'PRECIO' => 80.00,
                'CANTIDAD_VENDIDOS' => 1500,
                'PRECIO_CON_DESCUENTO' => 70.00,
                'PORCENTAJES_DESCUENTOS' => 12.5,
                'STOCK' => 1000,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Cereal+Nestl%C3%A9.jpg',
                'ID_VENDEDOR' => 10,
                'ID_CATEGORIA' => 5,
                'COLORES_DISPONIBLES' => 'Multicolor',
                'TIPO_ENVIO' => 'estándar',
                'FECHA_ENTREGA' => '2024-12-10',
                'COSTE_ENTREGA' => 10.00,
                'CALIFICACION' => 4.7,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Alimento rico en energía.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // Antigüedades y coleccionables
            [
                'MARCA' => 'Coleccionistas',
                'NOMBRE_PRODUCTO' => 'Moneda Antigua de Oro',
                'DESCRIPCION_PRODUCTO' => 'Moneda coleccionable de oro del siglo XIX.',
                'CARACTERISTICAS_PRODUCTO' => 'Certificada, en perfecto estado.',
                'PRECIO' => 10000.00,
                'CANTIDAD_VENDIDOS' => 10,
                'PRECIO_CON_DESCUENTO' => 9500.00,
                'PORCENTAJES_DESCUENTOS' => 5.0,
                'STOCK' => 5,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Moneda+Antigua.jpg',
                'ID_VENDEDOR' => 11,
                'ID_CATEGORIA' => 6,
                'COLORES_DISPONIBLES' => 'Dorado',
                'TIPO_ENVIO' => 'internacional',
                'FECHA_ENTREGA' => '2024-12-25',
                'COSTE_ENTREGA' => 50.00,
                'CALIFICACION' => 5.0,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Exclusiva y muy rara.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'MARCA' => 'Antigüedades',
                'NOMBRE_PRODUCTO' => 'Reloj de Bolsillo Antiguo',
                'DESCRIPCION_PRODUCTO' => 'Reloj de bolsillo antiguo, funcionando perfectamente.',
                'CARACTERISTICAS_PRODUCTO' => 'Acero inoxidable, con cadena.',
                'PRECIO' => 2500.00,
                'CANTIDAD_VENDIDOS' => 20,
                'PRECIO_CON_DESCUENTO' => 2400.00,
                'PORCENTAJES_DESCUENTOS' => 4.0,
                'STOCK' => 10,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Relog+de+Bolsillo+antiguo.jpg',
                'ID_VENDEDOR' => 12,
                'ID_CATEGORIA' => 6,
                'COLORES_DISPONIBLES' => 'Plateado',
                'TIPO_ENVIO' => 'internacional',
                'FECHA_ENTREGA' => '2024-12-28',
                'COSTE_ENTREGA' => 40.00,
                'CALIFICACION' => 4.9,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Ideal para coleccionistas.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // Arte, Papelería y Mercería
            [
                'MARCA' => 'Faber-Castell',
                'NOMBRE_PRODUCTO' => 'Lápices de Colores Faber-Castell',
                'DESCRIPCION_PRODUCTO' => 'Lápices de colores profesionales, perfectos para artistas.',
                'CARACTERISTICAS_PRODUCTO' => 'Set de 24 colores, alta calidad.',
                'PRECIO' => 120.00,
                'CANTIDAD_VENDIDOS' => 150,
                'PRECIO_CON_DESCUENTO' => 110.00,
                'PORCENTAJES_DESCUENTOS' => 8.3,
                'STOCK' => 50,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/L%C3%A1pices+de+Colores+Faber-Castell.jpg',
                'ID_VENDEDOR' => 13,
                'ID_CATEGORIA' => 7,
                'COLORES_DISPONIBLES' => 'Multicolor',
                'TIPO_ENVIO' => 'estándar',
                'FECHA_ENTREGA' => '2024-12-12',
                'COSTE_ENTREGA' => 10.00,
                'CALIFICACION' => 4.9,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Ideal para artistas profesionales.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'MARCA' => 'Staedtler',
                'NOMBRE_PRODUCTO' => 'Marcadores Permanentes Staedtler',
                'DESCRIPCION_PRODUCTO' => 'Marcadores permanentes, ideales para todo tipo de superficies.',
                'CARACTERISTICAS_PRODUCTO' => 'Set de 10 colores, tinta permanente.',
                'PRECIO' => 150.00,
                'CANTIDAD_VENDIDOS' => 200,
                'PRECIO_CON_DESCUENTO' => 130.00,
                'PORCENTAJES_DESCUENTOS' => 13.3,
                'STOCK' => 80,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Marcadores+Permanentes+Staedtler.jpg',
                'ID_VENDEDOR' => 14,
                'ID_CATEGORIA' => 7,
                'COLORES_DISPONIBLES' => 'Multicolor',
                'TIPO_ENVIO' => 'estándar',
                'FECHA_ENTREGA' => '2024-12-14',
                'COSTE_ENTREGA' => 10.00,
                'CALIFICACION' => 4.7,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Colores vivos y tinta duradera.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // Celulares y Telefonía
            [
                'MARCA' => 'Apple',
                'NOMBRE_PRODUCTO' => 'iPhone 14 Pro Max',
                'DESCRIPCION_PRODUCTO' => 'Smartphone de última generación con pantalla OLED y cámara de 48 MP.',
                'CARACTERISTICAS_PRODUCTO' => 'Pantalla de 6.7", 128GB, cámara triple.',
                'PRECIO' => 1200.00,
                'CANTIDAD_VENDIDOS' => 1000,
                'PRECIO_CON_DESCUENTO' => 1150.00,
                'PORCENTAJES_DESCUENTOS' => 4.2,
                'STOCK' => 200,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Iphone14+pro+max.jpg',
                'ID_VENDEDOR' => 15,
                'ID_CATEGORIA' => 8,
                'COLORES_DISPONIBLES' => 'Dorado, Gris',
                'TIPO_ENVIO' => 'express',
                'FECHA_ENTREGA' => '2024-12-10',
                'COSTE_ENTREGA' => 30.00,
                'CALIFICACION' => 4.9,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Rendimiento y diseño excepcional.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'MARCA' => 'Samsung',
                'NOMBRE_PRODUCTO' => 'Samsung Galaxy S23',
                'DESCRIPCION_PRODUCTO' => 'Smartphone con cámara de 50 MP y pantalla Dynamic AMOLED 2X.',
                'CARACTERISTICAS_PRODUCTO' => 'Pantalla de 6.1", 128GB, cámara cuádruple.',
                'PRECIO' => 900.00,
                'CANTIDAD_VENDIDOS' => 1500,
                'PRECIO_CON_DESCUENTO' => 850.00,
                'PORCENTAJES_DESCUENTOS' => 5.6,
                'STOCK' => 300,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Samsung+Galaxy+s23.jpg',
                'ID_VENDEDOR' => 16,
                'ID_CATEGORIA' => 8,
                'COLORES_DISPONIBLES' => 'Negro, Blanco, Azul',
                'TIPO_ENVIO' => 'express',
                'FECHA_ENTREGA' => '2024-12-12',
                'COSTE_ENTREGA' => 25.00,
                'CALIFICACION' => 4.7,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Rendimiento y calidad de cámara excepcionales.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // Computación
            [
                'MARCA' => 'HP',
                'NOMBRE_PRODUCTO' => 'Laptop HP Pavilion 15',
                'DESCRIPCION_PRODUCTO' => 'Laptop de alto rendimiento con procesador Intel Core i7.',
                'CARACTERISTICAS_PRODUCTO' => 'Pantalla de 15.6", 16GB RAM, 512GB SSD.',
                'PRECIO' => 750.00,
                'CANTIDAD_VENDIDOS' => 300,
                'PRECIO_CON_DESCUENTO' => 700.00,
                'PORCENTAJES_DESCUENTOS' => 6.7,
                'STOCK' => 150,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Laptop+HP+Pavilion+15.jpg',
                'ID_VENDEDOR' => 17,
                'ID_CATEGORIA' => 9,
                'COLORES_DISPONIBLES' => 'Plata, Negro',
                'TIPO_ENVIO' => 'estándar',
                'FECHA_ENTREGA' => '2024-12-20',
                'COSTE_ENTREGA' => 20.00,
                'CALIFICACION' => 4.8,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Gran rendimiento para tareas multitarea.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'MARCA' => 'Lenovo',
                'NOMBRE_PRODUCTO' => 'Lenovo ThinkPad X1 Carbon',
                'DESCRIPCION_PRODUCTO' => 'Laptop de negocios ultraligera con pantalla 14" UHD.',
                'CARACTERISTICAS_PRODUCTO' => 'Intel Core i7, 16GB RAM, 512GB SSD.',
                'PRECIO' => 1500.00,
                'CANTIDAD_VENDIDOS' => 100,
                'PRECIO_CON_DESCUENTO' => 1450.00,
                'PORCENTAJES_DESCUENTOS' => 3.3,
                'STOCK' => 50,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Lenovo+ThinkPad+X1+Carbon.jpg',
                'ID_VENDEDOR' => 18,
                'ID_CATEGORIA' => 9,
                'COLORES_DISPONIBLES' => 'Negro',
                'TIPO_ENVIO' => 'express',
                'FECHA_ENTREGA' => '2024-12-18',
                'COSTE_ENTREGA' => 30.00,
                'CALIFICACION' => 4.9,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Ultraligera y con gran rendimiento.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // Consolas y Videojuegos
            [
                'MARCA' => 'Sony',
                'NOMBRE_PRODUCTO' => 'PlayStation 5',
                'DESCRIPCION_PRODUCTO' => 'Consola de videojuegos de última generación con gráficos 4K.',
                'CARACTERISTICAS_PRODUCTO' => '8K, 4K a 120Hz, SSD ultra rápido, 825GB.',
                'PRECIO' => 4099.00,
                'CANTIDAD_VENDIDOS' => 500,
                'PRECIO_CON_DESCUENTO' => 479.00,
                'PORCENTAJES_DESCUENTOS' => 4.0,
                'STOCK' => 150,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Playstation+5.jpg',
                'ID_VENDEDOR' => 19,
                'ID_CATEGORIA' => 10,
                'COLORES_DISPONIBLES' => 'Blanco, Negro',
                'TIPO_ENVIO' => 'express',
                'FECHA_ENTREGA' => '2024-12-25',
                'COSTE_ENTREGA' => 40.00,
                'CALIFICACION' => 4.8,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Experiencia de juego inmersiva.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'MARCA' => 'Microsoft',
                'NOMBRE_PRODUCTO' => 'Xbox Series X',
                'DESCRIPCION_PRODUCTO' => 'Consola de videojuegos de alto rendimiento con soporte 4K.',
                'CARACTERISTICAS_PRODUCTO' => '8K, 4K a 120Hz, 1TB SSD.',
                'PRECIO' => 499.00,
                'CANTIDAD_VENDIDOS' => 400,
                'PRECIO_CON_DESCUENTO' => 479.00,
                'PORCENTAJES_DESCUENTOS' => 4.0,
                'STOCK' => 100,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Xbox+series+x.jpg',
                'ID_VENDEDOR' => 20,
                'ID_CATEGORIA' => 10,
                'COLORES_DISPONIBLES' => 'Negro',
                'TIPO_ENVIO' => 'express',
                'FECHA_ENTREGA' => '2024-12-30',
                'COSTE_ENTREGA' => 35.00,
                'CALIFICACION' => 4.9,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Rendimiento excepcional y gráficos ultra realistas.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // Construcción
            [
                'MARCA' => 'Bosch',
                'NOMBRE_PRODUCTO' => 'Taladro Bosch Professional',
                'DESCRIPCION_PRODUCTO' => 'Taladro profesional con 2 velocidades y 25 ajustes de par.',
                'CARACTERISTICAS_PRODUCTO' => '18V, batería de litio, velocidad variable.',
                'PRECIO' => 120.00,
                'CANTIDAD_VENDIDOS' => 150,
                'PRECIO_CON_DESCUENTO' => 110.00,
                'PORCENTAJES_DESCUENTOS' => 8.3,
                'STOCK' => 80,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Taladro+Bosch+Professional.jpg',
                'ID_VENDEDOR' => 21,
                'ID_CATEGORIA' => 11,
                'COLORES_DISPONIBLES' => 'Azul',
                'TIPO_ENVIO' => 'estándar',
                'FECHA_ENTREGA' => '2024-12-15',
                'COSTE_ENTREGA' => 15.00,
                'CALIFICACION' => 4.7,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Perfecto para tareas de bricolaje y profesionales.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'MARCA' => 'Makita',
                'NOMBRE_PRODUCTO' => 'Sierra Circular Makita',
                'DESCRIPCION_PRODUCTO' => 'Sierra circular de 7-1/4" con motor de alta potencia.',
                'CARACTERISTICAS_PRODUCTO' => 'Motor de 1800W, máxima profundidad de corte 66mm.',
                'PRECIO' => 150.00,
                'CANTIDAD_VENDIDOS' => 200,
                'PRECIO_CON_DESCUENTO' => 140.00,
                'PORCENTAJES_DESCUENTOS' => 6.7,
                'STOCK' => 100,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Sierra+Circular+Makita.jpg',
                'ID_VENDEDOR' => 22,
                'ID_CATEGORIA' => 11,
                'COLORES_DISPONIBLES' => 'Verde',
                'TIPO_ENVIO' => 'estándar',
                'FECHA_ENTREGA' => '2024-12-17',
                'COSTE_ENTREGA' => 20.00,
                'CALIFICACION' => 4.8,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Ideal para corte preciso y rápido.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],

            // Cámaras y Accesorios
            [
                'MARCA' => 'Canon',
                'NOMBRE_PRODUCTO' => 'Canon EOS 5D Mark IV',
                'DESCRIPCION_PRODUCTO' => 'Cámara DSLR profesional con sensor full-frame de 30.4 MP.',
                'CARACTERISTICAS_PRODUCTO' => 'Video 4K, pantalla táctil, Wi-Fi integrado.',
                'PRECIO' => 3000.00,
                'CANTIDAD_VENDIDOS' => 150,
                'PRECIO_CON_DESCUENTO' => 2800.00,
                'PORCENTAJES_DESCUENTOS' => 6.7,
                'STOCK' => 50,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Canon+EOS+5D+Mark+IV.jpg',
                'ID_VENDEDOR' => 23,
                'ID_CATEGORIA' => 12,
                'COLORES_DISPONIBLES' => 'Negro',
                'TIPO_ENVIO' => 'express',
                'FECHA_ENTREGA' => '2024-12-20',
                'COSTE_ENTREGA' => 30.00,
                'CALIFICACION' => 4.9,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Excelente calidad de imagen y video.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'MARCA' => 'Nikon',
                'NOMBRE_PRODUCTO' => 'Nikon D850',
                'DESCRIPCION_PRODUCTO' => 'Cámara DSLR de 45.7 MP con pantalla táctil y grabación 4K.',
                'CARACTERISTICAS_PRODUCTO' => '4K UHD, ISO 64-25600, 7 fps.',
                'PRECIO' => 3500.00,
                'CANTIDAD_VENDIDOS' => 100,
                'PRECIO_CON_DESCUENTO' => 3300.00,
                'PORCENTAJES_DESCUENTOS' => 5.7,
                'STOCK' => 40,
                'IMAGEN' => 'https://1752198-1mercadolibre.s3.us-east-2.amazonaws.com/productos/Nikon+D850.jpg',
                'ID_VENDEDOR' => 24,
                'ID_CATEGORIA' => 12,
                'COLORES_DISPONIBLES' => 'Negro',
                'TIPO_ENVIO' => 'express',
                'FECHA_ENTREGA' => '2024-12-25',
                'COSTE_ENTREGA' => 35.00,
                'CALIFICACION' => 4.8,
                'IVA' => 16.00,
                'CARACTERISTICAS' => 'Alta calidad de imagen y velocidad en enfoque.',
                'PRODUCTOS_TEMPORADA' => false,
                'created_at' => now(),
                'updated_at' => now()
            ]


            
            
        ]);
    }
}
